/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 11 02:53:25 GMT 2021
 */

package com.iluwatar.builder;

import org.junit.Test;
import static org.junit.Assert.*;
import com.iluwatar.builder.Profession;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Profession_ESTest extends Profession_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Profession[] professionArray0 = Profession.values();
      assertEquals(4, professionArray0.length);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Profession profession0 = Profession.valueOf("MAGE");
      String string0 = profession0.toString();
      assertEquals("mage", string0);
  }
}
