/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 11 02:12:47 GMT 2021
 */

package com.iluwatar.abstractdocument;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.iluwatar.abstractdocument.domain.Car;
import com.iluwatar.abstractdocument.domain.Part;
import java.util.HashMap;
import java.util.Map;
import java.util.function.Function;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class AbstractDocument_ESTest extends AbstractDocument_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      HashMap<String, Object> hashMap0 = new HashMap<String, Object>();
      Part part0 = new Part(hashMap0);
      Object object0 = part0.get((String) null);
      assertNull(object0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      HashMap<String, Object> hashMap0 = new HashMap<String, Object>();
      Car car0 = new Car(hashMap0);
      Object object0 = new Object();
      hashMap0.put("##;!33hH}ru", object0);
      Object object1 = car0.get("##;!33hH}ru");
      assertSame(object1, object0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      HashMap<String, Object> hashMap0 = new HashMap<String, Object>();
      Car car0 = new Car(hashMap0);
      // Undeclared exception!
      try { 
        car0.children("", (Function<Map<String, Object>, String>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      HashMap<String, Object> hashMap0 = new HashMap<String, Object>();
      Part part0 = new Part(hashMap0);
      String string0 = part0.toString();
      assertEquals("com.iluwatar.abstractdocument.domain.Part[]", string0);
  }
}
