/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 11 04:20:24 GMT 2021
 */

package com.iluwatar.databus.members;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.iluwatar.databus.AbstractDataType;
import com.iluwatar.databus.DataType;
import com.iluwatar.databus.data.MessageData;
import com.iluwatar.databus.members.MessageCollectorMember;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class MessageCollectorMember_ESTest extends MessageCollectorMember_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      MessageCollectorMember messageCollectorMember0 = new MessageCollectorMember("");
      AbstractDataType abstractDataType0 = new AbstractDataType();
      messageCollectorMember0.accept((DataType) abstractDataType0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      MessageCollectorMember messageCollectorMember0 = new MessageCollectorMember("%s sees message %s");
      DataType dataType0 = MessageData.of("%s sees message %s");
      // Undeclared exception!
      try { 
        messageCollectorMember0.accept(dataType0);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // Could not initialize class java.util.logging.LogRecord$CallerFinder
         //
         verifyException("java.util.logging.LogRecord", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      MessageCollectorMember messageCollectorMember0 = new MessageCollectorMember("%s sees message %s");
      List<String> list0 = messageCollectorMember0.getMessages();
      assertFalse(list0.contains("%s sees message %s"));
  }
}
