/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 11 04:53:48 GMT 2021
 */

package com.iluwatar.event.aggregator;

import org.junit.Test;
import static org.junit.Assert.*;
import com.iluwatar.event.aggregator.Event;
import com.iluwatar.event.aggregator.KingJoffrey;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class KingJoffrey_ESTest extends KingJoffrey_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      KingJoffrey kingJoffrey0 = new KingJoffrey();
      Event event0 = Event.WARSHIPS_APPROACHING;
      kingJoffrey0.onEvent(event0);
  }
}
