/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 11 12:48:18 GMT 2021
 */

package com.iluwatar.sharding;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.iluwatar.sharding.Data;
import com.iluwatar.sharding.RangeShardManager;
import com.iluwatar.sharding.Shard;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class RangeShardManager_ESTest extends RangeShardManager_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      RangeShardManager rangeShardManager0 = new RangeShardManager();
      Shard shard0 = new Shard(2);
      rangeShardManager0.addNewShard(shard0);
      Data.DataType data_DataType0 = Data.DataType.TYPE_2;
      Data data0 = new Data(2, "'BhR>%~A~Zl6N5nhq>", data_DataType0);
      int int0 = rangeShardManager0.storeData(data0);
      assertEquals(2, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      RangeShardManager rangeShardManager0 = new RangeShardManager();
      Data.DataType data_DataType0 = Data.DataType.TYPE_3;
      Data data0 = new Data(1045, "", data_DataType0);
      int int0 = rangeShardManager0.allocateShard(data0);
      assertEquals(3, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      RangeShardManager rangeShardManager0 = new RangeShardManager();
      // Undeclared exception!
      try { 
        rangeShardManager0.allocateShard((Data) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Cannot invoke \"com.iluwatar.sharding.Data.getType()\" because \"data\" is null
         //
         verifyException("com.iluwatar.sharding.RangeShardManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      RangeShardManager rangeShardManager0 = new RangeShardManager();
      Data.DataType data_DataType0 = Data.DataType.TYPE_3;
      Data data0 = new Data(2, "com.iluwatar.sharding.Shard", data_DataType0);
      // Undeclared exception!
      try { 
        rangeShardManager0.storeData(data0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Cannot invoke \"com.iluwatar.sharding.Shard.storeData(com.iluwatar.sharding.Data)\" because \"shard\" is null
         //
         verifyException("com.iluwatar.sharding.RangeShardManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      RangeShardManager rangeShardManager0 = new RangeShardManager();
      Data.DataType data_DataType0 = Data.DataType.TYPE_1;
      Data data0 = new Data(4178, "aJIADM2)WU", data_DataType0);
      // Undeclared exception!
      try { 
        rangeShardManager0.storeData(data0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Cannot invoke \"com.iluwatar.sharding.Shard.storeData(com.iluwatar.sharding.Data)\" because \"shard\" is null
         //
         verifyException("com.iluwatar.sharding.RangeShardManager", e);
      }
  }
}
