/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 11 03:52:24 GMT 2021
 */

package com.iluwatar.commander.shippingservice;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.iluwatar.commander.shippingservice.ShippingDatabase;
import com.iluwatar.commander.shippingservice.ShippingService;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.Random;
import org.evosuite.runtime.mock.java.lang.MockException;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class ShippingService_ESTest extends ShippingService_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      ShippingDatabase shippingDatabase0 = new ShippingDatabase();
      Exception[] exceptionArray0 = new Exception[0];
      ShippingService shippingService0 = new ShippingService(shippingDatabase0, exceptionArray0);
      Object[] objectArray0 = new Object[8];
      objectArray0[1] = (Object) "ADHKOSVZ37AD";
      String string0 = shippingService0.receiveRequest(objectArray0);
      assertEquals("ADHKOSVZ37AD", string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      ShippingService.ShippingRequest shippingService_ShippingRequest0 = new ShippingService.ShippingRequest("", "", "");
      Exception[] exceptionArray0 = new Exception[0];
      ShippingDatabase shippingDatabase0 = new ShippingDatabase();
      ShippingService shippingService0 = new ShippingService(shippingDatabase0, exceptionArray0);
      Object[] objectArray0 = new Object[6];
      objectArray0[0] = (Object) shippingService_ShippingRequest0;
      String string0 = shippingService0.updateDb(objectArray0);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      ShippingDatabase shippingDatabase0 = new ShippingDatabase();
      Exception[] exceptionArray0 = new Exception[2];
      MockException mockException0 = new MockException();
      exceptionArray0[0] = (Exception) mockException0;
      exceptionArray0[1] = (Exception) mockException0;
      ShippingService shippingService0 = new ShippingService(shippingDatabase0, exceptionArray0);
      Object[] objectArray0 = new Object[9];
      shippingService0.receiveRequest(objectArray0);
      Random.setNextRandom(0);
      String string0 = shippingService0.receiveRequest(objectArray0);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      ShippingDatabase shippingDatabase0 = new ShippingDatabase();
      Exception[] exceptionArray0 = new Exception[1];
      MockException mockException0 = new MockException();
      exceptionArray0[0] = (Exception) mockException0;
      ShippingService shippingService0 = new ShippingService(shippingDatabase0, exceptionArray0);
      // Undeclared exception!
      try { 
        shippingService0.updateDb(exceptionArray0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // class org.evosuite.runtime.mock.java.lang.MockException cannot be cast to class com.iluwatar.commander.shippingservice.ShippingService$ShippingRequest (org.evosuite.runtime.mock.java.lang.MockException is in unnamed module of loader 'app'; com.iluwatar.commander.shippingservice.ShippingService$ShippingRequest is in unnamed module of loader org.evosuite.instrumentation.InstrumentingClassLoader @6591076c)
         //
         verifyException("com.iluwatar.commander.shippingservice.ShippingService", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      ShippingDatabase shippingDatabase0 = new ShippingDatabase();
      Exception[] exceptionArray0 = new Exception[0];
      ShippingService shippingService0 = new ShippingService(shippingDatabase0, exceptionArray0);
      // Undeclared exception!
      try { 
        shippingService0.updateDb(exceptionArray0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 0 out of bounds for length 0
         //
         verifyException("com.iluwatar.commander.shippingservice.ShippingService", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      ShippingDatabase shippingDatabase0 = new ShippingDatabase();
      Exception[] exceptionArray0 = new Exception[1];
      MockException mockException0 = new MockException();
      exceptionArray0[0] = (Exception) mockException0;
      ShippingService shippingService0 = new ShippingService(shippingDatabase0, exceptionArray0);
      // Undeclared exception!
      try { 
        shippingService0.receiveRequest(exceptionArray0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // class org.evosuite.runtime.mock.java.lang.MockException cannot be cast to class java.lang.String (org.evosuite.runtime.mock.java.lang.MockException is in unnamed module of loader 'app'; java.lang.String is in module java.base of loader 'bootstrap')
         //
         verifyException("com.iluwatar.commander.shippingservice.ShippingService", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      ShippingDatabase shippingDatabase0 = new ShippingDatabase();
      Exception[] exceptionArray0 = new Exception[0];
      ShippingService shippingService0 = new ShippingService(shippingDatabase0, exceptionArray0);
      // Undeclared exception!
      try { 
        shippingService0.receiveRequest(exceptionArray0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 0 out of bounds for length 0
         //
         verifyException("com.iluwatar.commander.shippingservice.ShippingService", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      ShippingDatabase shippingDatabase0 = new ShippingDatabase();
      ShippingService shippingService0 = null;
      try {
        shippingService0 = new ShippingService(shippingDatabase0, (Exception[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Cannot read the array length because \"elements\" is null
         //
         verifyException("java.util.List", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      ShippingService.ShippingRequest shippingService_ShippingRequest0 = new ShippingService.ShippingRequest("EV!c`m2", "EV!c`m2", "EV!c`m2");
      Exception[] exceptionArray0 = new Exception[0];
      ShippingDatabase shippingDatabase0 = new ShippingDatabase();
      ShippingService shippingService0 = new ShippingService(shippingDatabase0, exceptionArray0);
      Object[] objectArray0 = new Object[6];
      objectArray0[0] = (Object) shippingService_ShippingRequest0;
      String string0 = shippingService0.updateDb(objectArray0);
      assertEquals("EV!c`m2", string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Exception[] exceptionArray0 = new Exception[0];
      ShippingDatabase shippingDatabase0 = new ShippingDatabase();
      ShippingService.ShippingRequest shippingService_ShippingRequest0 = new ShippingService.ShippingRequest("com.iluwatar.commander.exceptions.DatabaseUnavailableException", "com.iluwatar.commander.exceptions.DatabaseUnavailableException", "com.iluwatar.commander.exceptions.DatabaseUnavailableException");
      shippingDatabase0.add(shippingService_ShippingRequest0);
      ShippingService shippingService0 = new ShippingService(shippingDatabase0, exceptionArray0);
      Object[] objectArray0 = new Object[3];
      objectArray0[0] = (Object) shippingService_ShippingRequest0;
      String string0 = shippingService0.updateDb(objectArray0);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      ShippingDatabase shippingDatabase0 = new ShippingDatabase();
      Exception[] exceptionArray0 = new Exception[0];
      ShippingService shippingService0 = new ShippingService(shippingDatabase0, exceptionArray0);
      // Undeclared exception!
      try { 
        shippingService0.receiveRequest((Object[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Cannot load from object array because \"parameters\" is null
         //
         verifyException("com.iluwatar.commander.shippingservice.ShippingService", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Exception[] exceptionArray0 = new Exception[0];
      ShippingDatabase shippingDatabase0 = new ShippingDatabase();
      ShippingService shippingService0 = new ShippingService(shippingDatabase0, exceptionArray0);
      // Undeclared exception!
      try { 
        shippingService0.updateDb((Object[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Cannot load from object array because \"parameters\" is null
         //
         verifyException("com.iluwatar.commander.shippingservice.ShippingService", e);
      }
  }
}
