/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 11 04:41:14 GMT 2021
 */

package com.iluwatar.dirtyflag;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.iluwatar.dirtyflag.World;
import java.io.UncheckedIOException;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.testdata.EvoSuiteFile;
import org.evosuite.runtime.testdata.FileSystemHandling;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class World_ESTest extends World_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      World world0 = new World();
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("C:\\Users\\disto\\gitrepos\\java-design-patterns\\dirty-flag\\target\\classes\\world.txt");
      FileSystemHandling.shouldThrowIOException(evoSuiteFile0);
      FileSystemHandling.appendLineToFile(evoSuiteFile0, "com.iluwatar.dirtyflag.World");
      // Undeclared exception!
      try { 
        world0.fetch();
        fail("Expecting exception: UncheckedIOException");
      
      } catch(UncheckedIOException e) {
         //
         // java.io.IOException: Simulated IOException
         //
         verifyException("java.io.BufferedReader$1", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      World world0 = new World();
      List<String> list0 = world0.fetch();
      assertEquals(0, list0.size());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      World world0 = new World();
      EvoSuiteFile evoSuiteFile0 = new EvoSuiteFile("C:\\Users\\disto\\gitrepos\\java-design-patterns\\dirty-flag\\target\\classes\\world.txt");
      FileSystemHandling.appendLineToFile(evoSuiteFile0, "com.iluwatar.dirtyflag.World");
      List<String> list0 = world0.fetch();
      assertTrue(list0.contains("com.iluwatar.dirtyflag.World"));
  }
}
