/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 11 08:56:36 GMT 2021
 */

package com.iluwatar.lazy.loading;

import org.junit.Test;
import static org.junit.Assert.*;
import com.iluwatar.lazy.loading.Heavy;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Heavy_ESTest extends Heavy_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Heavy heavy0 = new Heavy();
  }
}
