/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 11 03:10:32 GMT 2021
 */

package com.iluwatar.chain;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.iluwatar.chain.OrcCommander;
import com.iluwatar.chain.OrcOfficer;
import com.iluwatar.chain.OrcSoldier;
import com.iluwatar.chain.Request;
import com.iluwatar.chain.RequestHandler;
import com.iluwatar.chain.RequestType;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class OrcCommander_ESTest extends OrcCommander_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      OrcCommander orcCommander0 = new OrcCommander((RequestHandler) null);
      // Undeclared exception!
      try { 
        orcCommander0.handleRequest((Request) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Cannot invoke \"com.iluwatar.chain.Request.getRequestType()\" because \"req\" is null
         //
         verifyException("com.iluwatar.chain.OrcCommander", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      RequestHandler requestHandler0 = mock(RequestHandler.class, new ViolatedAssumptionAnswer());
      OrcSoldier orcSoldier0 = new OrcSoldier(requestHandler0);
      OrcOfficer orcOfficer0 = new OrcOfficer(orcSoldier0);
      OrcCommander orcCommander0 = new OrcCommander(orcOfficer0);
      RequestType requestType0 = RequestType.DEFEND_CASTLE;
      Request request0 = new Request(requestType0, "aq'Ajv0v/J}q");
      orcCommander0.handleRequest(request0);
      assertTrue(request0.isHandled());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      RequestHandler requestHandler0 = mock(RequestHandler.class, new ViolatedAssumptionAnswer());
      OrcOfficer orcOfficer0 = new OrcOfficer(requestHandler0);
      OrcSoldier orcSoldier0 = new OrcSoldier(orcOfficer0);
      OrcCommander orcCommander0 = new OrcCommander(orcSoldier0);
      RequestType requestType0 = RequestType.COLLECT_TAX;
      Request request0 = new Request(requestType0, "Y,a#):[vL)\u0005],q");
      orcCommander0.handleRequest(request0);
      assertEquals("Y,a#):[vL)\u0005],q", request0.toString());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      OrcCommander orcCommander0 = new OrcCommander((RequestHandler) null);
      String string0 = orcCommander0.toString();
      assertEquals("Orc commander", string0);
  }
}
