/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 11 02:54:51 GMT 2021
 */

package com.iluwatar.business.delegate;

import org.junit.Test;
import static org.junit.Assert.*;
import com.iluwatar.business.delegate.BusinessLookup;
import com.iluwatar.business.delegate.BusinessService;
import com.iluwatar.business.delegate.EjbService;
import com.iluwatar.business.delegate.JmsService;
import com.iluwatar.business.delegate.ServiceType;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class BusinessLookup_ESTest extends BusinessLookup_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      BusinessLookup businessLookup0 = new BusinessLookup();
      ServiceType serviceType0 = ServiceType.EJB;
      EjbService ejbService0 = new EjbService();
      businessLookup0.setEjbService(ejbService0);
      BusinessService businessService0 = businessLookup0.getBusinessService(serviceType0);
      assertSame(businessService0, ejbService0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      BusinessLookup businessLookup0 = new BusinessLookup();
      ServiceType serviceType0 = ServiceType.EJB;
      BusinessService businessService0 = businessLookup0.getBusinessService(serviceType0);
      assertNull(businessService0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      BusinessLookup businessLookup0 = new BusinessLookup();
      ServiceType serviceType0 = ServiceType.JMS;
      BusinessService businessService0 = businessLookup0.getBusinessService(serviceType0);
      assertNull(businessService0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      BusinessLookup businessLookup0 = new BusinessLookup();
      JmsService jmsService0 = new JmsService();
      businessLookup0.setJmsService(jmsService0);
  }
}
