/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 11 02:55:07 GMT 2021
 */

package com.iluwatar.business.delegate;

import org.junit.Test;
import static org.junit.Assert.*;
import com.iluwatar.business.delegate.JmsService;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class JmsService_ESTest extends JmsService_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      JmsService jmsService0 = new JmsService();
      jmsService0.doProcessing();
  }
}
