/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 11 05:38:21 GMT 2021
 */

package com.iluwatar.featuretoggle.user;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.iluwatar.featuretoggle.user.User;
import com.iluwatar.featuretoggle.user.UserGroup;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class UserGroup_ESTest extends UserGroup_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      User user0 = new User("");
      UserGroup.addUserToPaidGroup(user0);
      boolean boolean0 = UserGroup.isPaid(user0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      User user0 = new User("");
      boolean boolean0 = UserGroup.isPaid(user0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      User user0 = new User("");
      UserGroup.addUserToPaidGroup(user0);
      UserGroup.addUserToPaidGroup(user0);
      assertEquals("", user0.toString());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      User user0 = new User("");
      UserGroup.addUserToFreeGroup(user0);
      try { 
        UserGroup.addUserToPaidGroup(user0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // User all ready member of free group.
         //
         verifyException("com.iluwatar.featuretoggle.user.UserGroup", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      User user0 = new User("");
      UserGroup.addUserToPaidGroup(user0);
      try { 
        UserGroup.addUserToFreeGroup(user0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // User all ready member of paid group.
         //
         verifyException("com.iluwatar.featuretoggle.user.UserGroup", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      User user0 = new User("");
      UserGroup.addUserToFreeGroup(user0);
      UserGroup.addUserToFreeGroup(user0);
      assertEquals("", user0.toString());
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      UserGroup userGroup0 = new UserGroup();
  }
}
