/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 11 05:37:13 GMT 2021
 */

package com.iluwatar.featuretoggle.user;

import org.junit.Test;
import static org.junit.Assert.*;
import com.iluwatar.featuretoggle.user.User;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class User_ESTest extends User_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      User user0 = new User((String) null);
      String string0 = user0.toString();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      User user0 = new User("_>xv3fx6");
      String string0 = user0.toString();
      assertEquals("_>xv3fx6", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      User user0 = new User("");
      String string0 = user0.toString();
      assertEquals("", string0);
  }
}
