/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 11 04:02:10 GMT 2021
 */

package com.iluwatar.cqrs.constants;

import org.junit.Test;
import static org.junit.Assert.*;
import com.iluwatar.cqrs.constants.AppConstants;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class AppConstants_ESTest extends AppConstants_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      AppConstants appConstants0 = new AppConstants();
  }
}
