/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 11 11:49:56 GMT 2021
 */

package com.iluwatar.registry;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.iluwatar.registry.Customer;
import com.iluwatar.registry.CustomerRegistry;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class CustomerRegistry_ESTest extends CustomerRegistry_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CustomerRegistry customerRegistry0 = CustomerRegistry.getInstance();
      Customer customer0 = customerRegistry0.getCustomer("+S]BwcCJX");
      assertNull(customer0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      CustomerRegistry customerRegistry0 = CustomerRegistry.getInstance();
      Customer customer0 = new Customer("", "");
      Customer customer1 = customerRegistry0.addCustomer(customer0);
      assertNull(customer1);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      CustomerRegistry customerRegistry0 = CustomerRegistry.getInstance();
      // Undeclared exception!
      try { 
        customerRegistry0.getCustomer((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      CustomerRegistry customerRegistry0 = CustomerRegistry.getInstance();
      Customer customer0 = customerRegistry0.getCustomer("");
      assertNull(customer0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      CustomerRegistry customerRegistry0 = CustomerRegistry.getInstance();
      // Undeclared exception!
      try { 
        customerRegistry0.addCustomer((Customer) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Cannot invoke \"com.iluwatar.registry.Customer.getId()\" because \"customer\" is null
         //
         verifyException("com.iluwatar.registry.CustomerRegistry", e);
      }
  }
}
