/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 11 05:20:53 GMT 2021
 */

package com.iluwatar.facade;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.iluwatar.facade.DwarvenCartOperator;
import com.iluwatar.facade.DwarvenGoldDigger;
import com.iluwatar.facade.DwarvenMineWorker;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class DwarvenMineWorker_ESTest extends DwarvenMineWorker_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      DwarvenCartOperator dwarvenCartOperator0 = new DwarvenCartOperator();
      String string0 = dwarvenCartOperator0.name();
      assertEquals("Dwarf cart operator", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      DwarvenCartOperator dwarvenCartOperator0 = new DwarvenCartOperator();
      DwarvenMineWorker.Action[] dwarvenMineWorker_ActionArray0 = new DwarvenMineWorker.Action[13];
      // Undeclared exception!
      try { 
        dwarvenCartOperator0.action(dwarvenMineWorker_ActionArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Cannot invoke \"com.iluwatar.facade.DwarvenMineWorker$Action.ordinal()\" because \"action\" is null
         //
         verifyException("com.iluwatar.facade.DwarvenMineWorker", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      DwarvenGoldDigger dwarvenGoldDigger0 = new DwarvenGoldDigger();
      dwarvenGoldDigger0.goHome();
      assertEquals("Dwarf gold digger", dwarvenGoldDigger0.name());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      DwarvenCartOperator dwarvenCartOperator0 = new DwarvenCartOperator();
      dwarvenCartOperator0.goToSleep();
      assertEquals("Dwarf cart operator", dwarvenCartOperator0.name());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      DwarvenCartOperator dwarvenCartOperator0 = new DwarvenCartOperator();
      DwarvenMineWorker.Action[] dwarvenMineWorker_ActionArray0 = DwarvenMineWorker.Action.values();
      dwarvenCartOperator0.action(dwarvenMineWorker_ActionArray0);
      assertEquals(5, dwarvenMineWorker_ActionArray0.length);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      DwarvenGoldDigger dwarvenGoldDigger0 = new DwarvenGoldDigger();
      dwarvenGoldDigger0.wakeUp();
      assertEquals("Dwarf gold digger", dwarvenGoldDigger0.name());
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      DwarvenGoldDigger dwarvenGoldDigger0 = new DwarvenGoldDigger();
      dwarvenGoldDigger0.goToMine();
      assertEquals("Dwarf gold digger", dwarvenGoldDigger0.name());
  }
}
