/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 11 12:27:53 GMT 2021
 */

package com.iluwatar.servant;

import org.junit.Test;
import static org.junit.Assert.*;
import com.iluwatar.servant.King;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class King_ESTest extends King_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      King king0 = new King();
      king0.getFed();
      king0.getDrink();
      king0.changeMood();
      boolean boolean0 = king0.getMood();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      King king0 = new King();
      king0.changeMood();
      assertFalse(king0.getMood());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      King king0 = new King();
      king0.getFed();
      king0.changeMood();
      assertFalse(king0.getMood());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      King king0 = new King();
      king0.receiveCompliments();
      king0.changeMood();
      assertFalse(king0.getMood());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      King king0 = new King();
      boolean boolean0 = king0.getMood();
      assertFalse(boolean0);
  }
}
