/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 11 03:56:12 GMT 2021
 */

package com.iluwatar.composite;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.iluwatar.composite.Letter;
import com.iluwatar.composite.Word;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Word_ESTest extends Word_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Word word0 = null;
      try {
        word0 = new Word((char[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Cannot read the array length because \"<local2>\" is null
         //
         verifyException("com.iluwatar.composite.Word", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Word word0 = null;
      try {
        word0 = new Word((List<Letter>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Cannot invoke \"java.util.List.forEach(java.util.function.Consumer)\" because \"letters\" is null
         //
         verifyException("com.iluwatar.composite.Word", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      char[] charArray0 = new char[2];
      Word word0 = new Word(charArray0);
      word0.printThisBefore();
      assertEquals(2, word0.count());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      List<Letter> list0 = List.of();
      Word word0 = new Word(list0);
      assertEquals(0, word0.count());
  }
}
