/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 11 11:53:01 GMT 2021
 */

package com.iluwatar.retry;

import org.junit.Test;
import static org.junit.Assert.*;
import com.iluwatar.retry.BusinessException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class BusinessException_ESTest extends BusinessException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      BusinessException businessException0 = new BusinessException("\"B)W\"'`qVP7 l0!bQ");
  }
}
