/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 11 03:23:24 GMT 2021
 */

package com.iluwatar.collectionpipeline;

import org.junit.Test;
import static org.junit.Assert.*;
import com.iluwatar.collectionpipeline.Car;
import com.iluwatar.collectionpipeline.Category;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Car_ESTest extends Car_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Category category0 = Category.JEEP;
      Car car0 = new Car("2", "2", 0, category0);
      Car car1 = new Car("2", "2", (-1040), category0);
      boolean boolean0 = car1.equals(car0);
      assertFalse(boolean0);
      assertEquals((-1040), car1.getYear());
      assertFalse(car0.equals((Object)car1));
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Category category0 = Category.SEDAN;
      Car car0 = new Car((String) null, "qqd@t=|$@k-", 73, category0);
      int int0 = car0.getYear();
      assertEquals(73, int0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Category category0 = Category.JEEP;
      Car car0 = new Car("2", "2", (-1040), category0);
      int int0 = car0.getYear();
      assertEquals((-1040), int0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Category category0 = Category.CONVERTIBLE;
      Car car0 = new Car((String) null, (String) null, 2733, category0);
      car0.getModel();
      assertEquals(2733, car0.getYear());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Category category0 = Category.CONVERTIBLE;
      Car car0 = new Car("", "", (-1091), category0);
      car0.getModel();
      assertEquals((-1091), car0.getYear());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Category category0 = Category.CONVERTIBLE;
      Car car0 = new Car((String) null, (String) null, 2733, category0);
      car0.getMake();
      assertEquals(2733, car0.getYear());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Category category0 = Category.CONVERTIBLE;
      Car car0 = new Car("", "", (-1091), category0);
      car0.getMake();
      assertEquals((-1091), car0.getYear());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Car car0 = new Car("1UNxD d,Wf>,3", "1UNxD-d,Wf>,3", 250, (Category) null);
      car0.getCategory();
      assertEquals("1UNxD-d,Wf>,3", car0.getModel());
      assertEquals(250, car0.getYear());
      assertEquals("1UNxD d,Wf>,3", car0.getMake());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Category category0 = Category.SEDAN;
      Car car0 = new Car((String) null, (String) null, 73, category0);
      Car car1 = new Car((String) null, "$VALUES", 73, category0);
      boolean boolean0 = car1.equals(car0);
      assertEquals(73, car1.getYear());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Category category0 = Category.SEDAN;
      Car car0 = new Car((String) null, (String) null, 73, category0);
      Car car1 = new Car((String) null, "com.iluwatar.collectionpipeline.Car", 69, category0);
      boolean boolean0 = car0.equals(car1);
      assertFalse(boolean0);
      assertEquals(69, car1.getYear());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Category category0 = Category.SEDAN;
      Car car0 = new Car("1UNxD d,Wf>,7", "1UNxD d,Wf>,7", (-454), category0);
      Car car1 = new Car("1UNxD d,Wf>,3", "1UNxD d,Wf>,3", (-454), category0);
      boolean boolean0 = car0.equals(car1);
      assertEquals((-454), car1.getYear());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Category category0 = Category.SEDAN;
      Car car0 = new Car((String) null, (String) null, 73, category0);
      Car car1 = new Car("=EU+IqK@ET5{Fzt", "_V{M57tJ))rjd", (-1879048189), category0);
      boolean boolean0 = car0.equals(car1);
      assertEquals((-1879048189), car1.getYear());
      assertEquals("=EU+IqK@ET5{Fzt", car1.getMake());
      assertEquals("_V{M57tJ))rjd", car1.getModel());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Category category0 = Category.SEDAN;
      Car car0 = new Car((String) null, (String) null, 73, category0);
      Car car1 = new Car((String) null, (String) null, 73, category0);
      boolean boolean0 = car0.equals(car1);
      assertTrue(boolean0);
      assertEquals(73, car1.getYear());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Category category0 = Category.SEDAN;
      Car car0 = new Car("1UNxD-d,Wf>,3", "1UNxD-d,Wf>,3", 1277, category0);
      Car car1 = new Car("1UNxD d,Wf>,3", "1UNxD-d,Wf>,3", 250, (Category) null);
      boolean boolean0 = car1.equals(car0);
      assertEquals("1UNxD d,Wf>,3", car1.getMake());
      assertFalse(boolean0);
      assertEquals("1UNxD-d,Wf>,3", car1.getModel());
      assertEquals(250, car1.getYear());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Category category0 = Category.JEEP;
      Car car0 = new Car("2", "2", 0, category0);
      Car car1 = new Car("2", "2", (-1040), category0);
      boolean boolean0 = car0.equals(car1);
      assertFalse(boolean0);
      assertFalse(car1.equals((Object)car0));
      assertEquals((-1040), car1.getYear());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Category category0 = Category.CONVERTIBLE;
      Car car0 = new Car((String) null, (String) null, 879, category0);
      boolean boolean0 = car0.equals((Object) null);
      assertFalse(boolean0);
      assertEquals(879, car0.getYear());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Category category0 = Category.JEEP;
      Car car0 = new Car("0Z>?k_bu=yvv.V5$z8;", "0Z>?k_bu=yvv.V5$z8;", 2612, category0);
      boolean boolean0 = car0.equals(car0);
      assertTrue(boolean0);
      assertEquals(2612, car0.getYear());
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Category category0 = Category.JEEP;
      Car car0 = new Car("2", "2", 0, category0);
      boolean boolean0 = car0.equals("2");
      assertEquals(0, car0.getYear());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Category category0 = Category.SEDAN;
      Car car0 = new Car((String) null, (String) null, 73, category0);
      car0.hashCode();
      assertEquals(73, car0.getYear());
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Car car0 = new Car("1UNxD d,Wf>,3", "1UNxD-d,Wf>,3", 250, (Category) null);
      car0.hashCode();
      assertEquals("1UNxD d,Wf>,3", car0.getMake());
      assertEquals("1UNxD-d,Wf>,3", car0.getModel());
      assertEquals(250, car0.getYear());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Category category0 = Category.JEEP;
      Car car0 = new Car("2", "2", 0, category0);
      car0.getMake();
      assertEquals(0, car0.getYear());
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Category category0 = Category.JEEP;
      Car car0 = new Car("2", "2", 0, category0);
      int int0 = car0.getYear();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Category category0 = Category.JEEP;
      Car car0 = new Car("2", "2", 0, category0);
      car0.getCategory();
      assertEquals(0, car0.getYear());
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Category category0 = Category.JEEP;
      Car car0 = new Car("2", "2", 0, category0);
      car0.getModel();
      assertEquals(0, car0.getYear());
  }
}
