/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 11 05:13:31 GMT 2021
 */

package com.iluwatar.execute.around;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.iluwatar.execute.around.FileWriterAction;
import com.iluwatar.execute.around.SimpleFileWriter;
import java.io.FileNotFoundException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class SimpleFileWriter_ESTest extends SimpleFileWriter_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      FileWriterAction fileWriterAction0 = mock(FileWriterAction.class, new ViolatedAssumptionAnswer());
      SimpleFileWriter simpleFileWriter0 = new SimpleFileWriter("~mi^[K}u5UjiP&", fileWriterAction0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      SimpleFileWriter simpleFileWriter0 = null;
      try {
        simpleFileWriter0 = new SimpleFileWriter((String) null, (FileWriterAction) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.io.File", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      SimpleFileWriter simpleFileWriter0 = null;
      try {
        simpleFileWriter0 = new SimpleFileWriter("2WKNJ$967fK;!", (FileWriterAction) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Cannot invoke \"com.iluwatar.execute.around.FileWriterAction.writeFile(java.io.FileWriter)\" because \"action\" is null
         //
         verifyException("com.iluwatar.execute.around.SimpleFileWriter", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      SimpleFileWriter simpleFileWriter0 = null;
      try {
        simpleFileWriter0 = new SimpleFileWriter("", (FileWriterAction) null);
        fail("Expecting exception: FileNotFoundException");
      
      } catch(Throwable e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.evosuite.runtime.mock.java.io.MockFileOutputStream", e);
      }
  }
}
