/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 11 04:44:35 GMT 2021
 */

package com.iluwatar.doublebuffer;

import org.junit.Test;
import static org.junit.Assert.*;
import com.iluwatar.doublebuffer.Pixel;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Pixel_ESTest extends Pixel_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Pixel[] pixelArray0 = Pixel.values();
      assertEquals(2, pixelArray0.length);
  }
}
