/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 11 02:38:09 GMT 2021
 */

package com.iluwatar.arrangeactassert;

import org.junit.Test;
import static org.junit.Assert.*;
import com.iluwatar.arrangeactassert.Cash;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Cash_ESTest extends Cash_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Cash cash0 = new Cash((-1));
      cash0.plus(4753);
      boolean boolean0 = cash0.minus(137);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Cash cash0 = new Cash((-1));
      cash0.plus(4753);
      int int0 = cash0.count();
      assertEquals(4752, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Cash cash0 = new Cash((-1));
      boolean boolean0 = cash0.minus((-1));
      assertTrue(boolean0);
      
      int int0 = cash0.count();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Cash cash0 = new Cash((-1));
      boolean boolean0 = cash0.minus(137);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Cash cash0 = new Cash((-1));
      int int0 = cash0.count();
      assertEquals((-1), int0);
  }
}
