/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 11 10:41:27 GMT 2021
 */

package com.iluwatar.priority.queue;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.iluwatar.priority.queue.Message;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Message_ESTest extends Message_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Message message0 = new Message("[6", 0);
      int int0 = message0.compareTo(message0);
      assertEquals(0, int0);
      assertEquals("Message{message='[6', priority=0}", message0.toString());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Message message0 = new Message("", 1);
      Message message1 = new Message("", 7032);
      int int0 = message1.compareTo(message0);
      assertEquals("Message{message='', priority=7032}", message1.toString());
      assertEquals(7031, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Message message0 = new Message("", 1);
      Message message1 = new Message("", 7032);
      int int0 = message0.compareTo(message1);
      assertEquals("Message{message='', priority=7032}", message1.toString());
      assertEquals((-7031), int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Message message0 = new Message("", 1);
      String string0 = message0.toString();
      assertEquals("Message{message='', priority=1}", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Message message0 = new Message("N", 0);
      // Undeclared exception!
      try { 
        message0.compareTo((Message) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Cannot read field \"priority\"
         //
         verifyException("com.iluwatar.priority.queue.Message", e);
      }
  }
}
