/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 11 10:42:38 GMT 2021
 */

package com.iluwatar.priority.queue;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.iluwatar.priority.queue.PriorityMessageQueue;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class PriorityMessageQueue_ESTest extends PriorityMessageQueue_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      String[] stringArray0 = new String[14];
      PriorityMessageQueue<String> priorityMessageQueue0 = new PriorityMessageQueue<String>(stringArray0);
      priorityMessageQueue0.add("^d");
      priorityMessageQueue0.add("^d");
      priorityMessageQueue0.print();
      assertFalse(priorityMessageQueue0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      String[] stringArray0 = new String[14];
      PriorityMessageQueue<String> priorityMessageQueue0 = new PriorityMessageQueue<String>(stringArray0);
      priorityMessageQueue0.add("^d");
      priorityMessageQueue0.add("=5p.mPu");
      priorityMessageQueue0.add("=5p.mPu");
      priorityMessageQueue0.add("Hri1");
      String string0 = priorityMessageQueue0.remove();
      assertEquals("^d", string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      String[] stringArray0 = new String[1];
      PriorityMessageQueue<String> priorityMessageQueue0 = new PriorityMessageQueue<String>(stringArray0);
      // Undeclared exception!
      try { 
        priorityMessageQueue0.print();
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      String[] stringArray0 = new String[2];
      PriorityMessageQueue<String> priorityMessageQueue0 = new PriorityMessageQueue<String>(stringArray0);
      // Undeclared exception!
      try { 
        priorityMessageQueue0.add((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Cannot invoke \"java.lang.Comparable.compareTo(Object)\" because the return value of \"com.iluwatar.priority.queue.PriorityMessageQueue.parent(int)\" is null
         //
         verifyException("com.iluwatar.priority.queue.PriorityMessageQueue", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      String[] stringArray0 = new String[0];
      PriorityMessageQueue<String> priorityMessageQueue0 = new PriorityMessageQueue<String>(stringArray0);
      // Undeclared exception!
      try { 
        priorityMessageQueue0.add("");
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 0 out of bounds for length 0
         //
         verifyException("com.iluwatar.priority.queue.PriorityMessageQueue", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      PriorityMessageQueue<String> priorityMessageQueue0 = null;
      try {
        priorityMessageQueue0 = new PriorityMessageQueue<String>((String[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Cannot read the array length because \"queue\" is null
         //
         verifyException("com.iluwatar.priority.queue.PriorityMessageQueue", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      String[] stringArray0 = new String[14];
      PriorityMessageQueue<String> priorityMessageQueue0 = new PriorityMessageQueue<String>(stringArray0);
      priorityMessageQueue0.add("^d");
      boolean boolean0 = priorityMessageQueue0.isEmpty();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      String[] stringArray0 = new String[2];
      PriorityMessageQueue<String> priorityMessageQueue0 = new PriorityMessageQueue<String>(stringArray0);
      boolean boolean0 = priorityMessageQueue0.isEmpty();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      String[] stringArray0 = new String[1];
      PriorityMessageQueue<String> priorityMessageQueue0 = new PriorityMessageQueue<String>(stringArray0);
      priorityMessageQueue0.add(";P<A");
      priorityMessageQueue0.add(";P<A");
      assertFalse(priorityMessageQueue0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      String[] stringArray0 = new String[14];
      PriorityMessageQueue<String> priorityMessageQueue0 = new PriorityMessageQueue<String>(stringArray0);
      priorityMessageQueue0.add("^d");
      priorityMessageQueue0.add("Le6 )g");
      priorityMessageQueue0.add("^d");
      priorityMessageQueue0.remove();
      assertFalse(priorityMessageQueue0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      String[] stringArray0 = new String[14];
      PriorityMessageQueue<String> priorityMessageQueue0 = new PriorityMessageQueue<String>(stringArray0);
      priorityMessageQueue0.add("");
      priorityMessageQueue0.add("");
      priorityMessageQueue0.add("");
      priorityMessageQueue0.add("");
      priorityMessageQueue0.remove();
      assertFalse(priorityMessageQueue0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      String[] stringArray0 = new String[14];
      PriorityMessageQueue<String> priorityMessageQueue0 = new PriorityMessageQueue<String>(stringArray0);
      assertTrue(priorityMessageQueue0.isEmpty());
      
      priorityMessageQueue0.add("^d");
      priorityMessageQueue0.add("^d");
      priorityMessageQueue0.add("^d");
      priorityMessageQueue0.remove();
      assertFalse(priorityMessageQueue0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      String[] stringArray0 = new String[1];
      PriorityMessageQueue<String> priorityMessageQueue0 = new PriorityMessageQueue<String>(stringArray0);
      String string0 = priorityMessageQueue0.remove();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      String[] stringArray0 = new String[13];
      PriorityMessageQueue<String> priorityMessageQueue0 = new PriorityMessageQueue<String>(stringArray0);
      assertTrue(priorityMessageQueue0.isEmpty());
      
      priorityMessageQueue0.add(";");
      priorityMessageQueue0.add("cI");
      priorityMessageQueue0.add("cI");
      priorityMessageQueue0.add(";");
      priorityMessageQueue0.remove();
      assertFalse(priorityMessageQueue0.isEmpty());
  }
}
