/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 11 10:42:44 GMT 2021
 */

package com.iluwatar.priority.queue;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.iluwatar.priority.queue.Message;
import com.iluwatar.priority.queue.QueueManager;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class QueueManager_ESTest extends QueueManager_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      QueueManager queueManager0 = new QueueManager(0);
      // Undeclared exception!
      try { 
        queueManager0.publishMessage((Message) null);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // Index 0 out of bounds for length 0
         //
         verifyException("com.iluwatar.priority.queue.PriorityMessageQueue", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      QueueManager queueManager0 = new QueueManager(400);
      Message message0 = queueManager0.receiveMessage();
      assertNull(message0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      QueueManager queueManager0 = new QueueManager(400);
      Message message0 = new Message("com.iluwatar.priority.queue.QueueManager", 400);
      queueManager0.publishMessage(message0);
      Message message1 = queueManager0.receiveMessage();
      assertSame(message1, message0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      QueueManager queueManager0 = new QueueManager(1622);
      // Undeclared exception!
      try { 
        queueManager0.publishMessage((Message) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Cannot invoke \"java.lang.Comparable.compareTo(Object)\" because the return value of \"com.iluwatar.priority.queue.PriorityMessageQueue.parent(int)\" is null
         //
         verifyException("com.iluwatar.priority.queue.PriorityMessageQueue", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      QueueManager queueManager0 = null;
      try {
        queueManager0 = new QueueManager((-534));
        fail("Expecting exception: NegativeArraySizeException");
      
      } catch(NegativeArraySizeException e) {
         //
         // -534
         //
         verifyException("com.iluwatar.priority.queue.QueueManager", e);
      }
  }
}
