/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 11 10:43:58 GMT 2021
 */

package com.iluwatar.priority.queue;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.iluwatar.priority.queue.QueueManager;
import com.iluwatar.priority.queue.Worker;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Worker_ESTest extends Worker_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Worker worker0 = new Worker((QueueManager) null);
      try { 
        worker0.run();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Cannot invoke \"com.iluwatar.priority.queue.QueueManager.receiveMessage()\" because \"this.queueManager\" is null
         //
         verifyException("com.iluwatar.priority.queue.Worker", e);
      }
  }
}
