/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 11 12:27:22 GMT 2021
 */

package com.iluwatar.separatedinterface;

import org.junit.Test;
import static org.junit.Assert.*;
import com.iluwatar.separatedinterface.App;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class App_ESTest extends App_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      String[] stringArray0 = new String[0];
      App.main(stringArray0);
      assertEquals(0, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      App app0 = new App();
      assertEquals(50.0, App.PRODUCT_COST, 0.01);
  }
}
