/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 11 04:48:36 GMT 2021
 */

package com.iluwatar.doubledispatch;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.iluwatar.doubledispatch.FlamingAsteroid;
import com.iluwatar.doubledispatch.GameObject;
import com.iluwatar.doubledispatch.Meteoroid;
import com.iluwatar.doubledispatch.SpaceStationIss;
import com.iluwatar.doubledispatch.SpaceStationMir;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Meteoroid_ESTest extends Meteoroid_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      FlamingAsteroid flamingAsteroid0 = new FlamingAsteroid(1, 1, 1, 1);
      flamingAsteroid0.collisionResolve(flamingAsteroid0);
      assertEquals(1, flamingAsteroid0.getTop());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      FlamingAsteroid flamingAsteroid0 = new FlamingAsteroid(1, 1, 1, 1);
      SpaceStationIss spaceStationIss0 = new SpaceStationIss(400, 400, 1632, (-3125));
      flamingAsteroid0.collisionResolve(spaceStationIss0);
      assertEquals(1, flamingAsteroid0.getTop());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      FlamingAsteroid flamingAsteroid0 = new FlamingAsteroid(0, 964, 0, 0);
      // Undeclared exception!
      try { 
        flamingAsteroid0.collisionResolve((SpaceStationMir) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Cannot invoke \"Object.getClass()\" because \"mir\" is null
         //
         verifyException("com.iluwatar.doubledispatch.Meteoroid", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      FlamingAsteroid flamingAsteroid0 = new FlamingAsteroid((-1), (-918), 2, 1);
      // Undeclared exception!
      try { 
        flamingAsteroid0.collisionResolve((Meteoroid) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Cannot invoke \"Object.getClass()\"
         //
         verifyException("com.iluwatar.doubledispatch.Meteoroid", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Meteoroid meteoroid0 = new Meteoroid(0, 4, 0, 0);
      // Undeclared exception!
      try { 
        meteoroid0.collisionResolve((FlamingAsteroid) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Cannot invoke \"Object.getClass()\" because \"asteroid\" is null
         //
         verifyException("com.iluwatar.doubledispatch.Meteoroid", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Meteoroid meteoroid0 = new Meteoroid(0, (-1), 0, (-550));
      // Undeclared exception!
      try { 
        meteoroid0.collision((GameObject) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Cannot invoke \"com.iluwatar.doubledispatch.GameObject.collisionResolve(com.iluwatar.doubledispatch.Meteoroid)\" because \"gameObject\" is null
         //
         verifyException("com.iluwatar.doubledispatch.Meteoroid", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      FlamingAsteroid flamingAsteroid0 = new FlamingAsteroid(1, 1, 1, 1);
      flamingAsteroid0.collisionResolve((Meteoroid) flamingAsteroid0);
      assertTrue(flamingAsteroid0.isOnFire());
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      FlamingAsteroid flamingAsteroid0 = new FlamingAsteroid(1, 1, 1, 1);
      SpaceStationIss spaceStationIss0 = new SpaceStationIss(400, 400, 1632, (-3125));
      flamingAsteroid0.collisionResolve((SpaceStationMir) spaceStationIss0);
      assertFalse(spaceStationIss0.isDamaged());
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      Meteoroid meteoroid0 = new Meteoroid(0, (-1), 0, (-550));
      meteoroid0.collision(meteoroid0);
      assertFalse(meteoroid0.isOnFire());
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      Meteoroid meteoroid0 = new Meteoroid((-432), (-432), (-432), (-432));
      // Undeclared exception!
      try { 
        meteoroid0.collisionResolve((SpaceStationIss) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Cannot invoke \"Object.getClass()\" because \"iss\" is null
         //
         verifyException("com.iluwatar.doubledispatch.Meteoroid", e);
      }
  }
}
