/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 11 13:22:15 GMT 2021
 */

package com.iluwatar.strangler;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.iluwatar.strangler.OldArithmetic;
import com.iluwatar.strangler.OldSource;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class OldArithmetic_ESTest extends OldArithmetic_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      OldSource oldSource0 = new OldSource();
      int[] intArray0 = new int[8];
      intArray0[0] = 966;
      OldArithmetic oldArithmetic0 = new OldArithmetic(oldSource0);
      int int0 = oldArithmetic0.sum(intArray0);
      assertEquals(966, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      OldSource oldSource0 = new OldSource();
      OldArithmetic oldArithmetic0 = new OldArithmetic(oldSource0);
      int[] intArray0 = new int[1];
      intArray0[0] = (-1);
      int int0 = oldArithmetic0.sum(intArray0);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      OldSource oldSource0 = new OldSource();
      OldArithmetic oldArithmetic0 = new OldArithmetic(oldSource0);
      int[] intArray0 = new int[0];
      int int0 = oldArithmetic0.mul(intArray0);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      OldSource oldSource0 = new OldSource();
      OldArithmetic oldArithmetic0 = new OldArithmetic(oldSource0);
      int[] intArray0 = new int[1];
      intArray0[0] = (-1);
      int int0 = oldArithmetic0.mul(intArray0);
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      OldSource oldSource0 = new OldSource();
      OldArithmetic oldArithmetic0 = new OldArithmetic(oldSource0);
      // Undeclared exception!
      try { 
        oldArithmetic0.sum((int[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Cannot read the array length because \"<local3>\" is null
         //
         verifyException("com.iluwatar.strangler.OldSource", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      OldSource oldSource0 = new OldSource();
      OldArithmetic oldArithmetic0 = new OldArithmetic(oldSource0);
      // Undeclared exception!
      try { 
        oldArithmetic0.mul((int[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Cannot read the array length because \"<local3>\" is null
         //
         verifyException("com.iluwatar.strangler.OldSource", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      OldSource oldSource0 = new OldSource();
      OldArithmetic oldArithmetic0 = new OldArithmetic(oldSource0);
      int[] intArray0 = new int[1];
      int int0 = oldArithmetic0.mul(intArray0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      OldSource oldSource0 = new OldSource();
      OldArithmetic oldArithmetic0 = new OldArithmetic(oldSource0);
      int[] intArray0 = new int[1];
      int int0 = oldArithmetic0.sum(intArray0);
      assertEquals(0, int0);
  }
}
