/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 11 05:03:14 GMT 2021
 */

package com.iluwatar.eda.handler;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.iluwatar.eda.event.UserCreatedEvent;
import com.iluwatar.eda.handler.UserCreatedEventHandler;
import com.iluwatar.eda.model.User;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class UserCreatedEventHandler_ESTest extends UserCreatedEventHandler_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      UserCreatedEventHandler userCreatedEventHandler0 = new UserCreatedEventHandler();
      // Undeclared exception!
      try { 
        userCreatedEventHandler0.onEvent((UserCreatedEvent) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Cannot invoke \"com.iluwatar.eda.event.UserCreatedEvent.getUser()\" because \"event\" is null
         //
         verifyException("com.iluwatar.eda.handler.UserCreatedEventHandler", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      UserCreatedEventHandler userCreatedEventHandler0 = new UserCreatedEventHandler();
      User user0 = new User("com.iluwatar.eda.event.UserCreatedEvent");
      UserCreatedEvent userCreatedEvent0 = new UserCreatedEvent(user0);
      userCreatedEventHandler0.onEvent(userCreatedEvent0);
  }
}
