/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 11 04:32:39 GMT 2021
 */

package com.iluwatar.dependency.injection;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.iluwatar.dependency.injection.AdvancedWizard;
import com.iluwatar.dependency.injection.OldTobyTobacco;
import com.iluwatar.dependency.injection.Tobacco;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class AdvancedWizard_ESTest extends AdvancedWizard_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      AdvancedWizard advancedWizard0 = new AdvancedWizard((Tobacco) null);
      // Undeclared exception!
      try { 
        advancedWizard0.smoke();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Cannot invoke \"com.iluwatar.dependency.injection.Tobacco.smoke(com.iluwatar.dependency.injection.Wizard)\" because \"this.tobacco\" is null
         //
         verifyException("com.iluwatar.dependency.injection.AdvancedWizard", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      OldTobyTobacco oldTobyTobacco0 = new OldTobyTobacco();
      AdvancedWizard advancedWizard0 = new AdvancedWizard(oldTobyTobacco0);
      advancedWizard0.smoke();
  }
}
