/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 11 04:34:17 GMT 2021
 */

package com.iluwatar.dependency.injection;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.iluwatar.dependency.injection.AdvancedSorceress;
import com.iluwatar.dependency.injection.SecondBreakfastTobacco;
import com.iluwatar.dependency.injection.Wizard;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Tobacco_ESTest extends Tobacco_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SecondBreakfastTobacco secondBreakfastTobacco0 = new SecondBreakfastTobacco();
      // Undeclared exception!
      try { 
        secondBreakfastTobacco0.smoke((Wizard) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Cannot invoke \"Object.getClass()\" because \"wizard\" is null
         //
         verifyException("com.iluwatar.dependency.injection.Tobacco", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      SecondBreakfastTobacco secondBreakfastTobacco0 = new SecondBreakfastTobacco();
      AdvancedSorceress advancedSorceress0 = new AdvancedSorceress();
      secondBreakfastTobacco0.smoke(advancedSorceress0);
  }
}
