/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 11 05:02:57 GMT 2021
 */

package com.iluwatar.eda.event;

import org.junit.Test;
import static org.junit.Assert.*;
import com.iluwatar.eda.event.UserCreatedEvent;
import com.iluwatar.eda.model.User;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class UserCreatedEvent_ESTest extends UserCreatedEvent_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      UserCreatedEvent userCreatedEvent0 = new UserCreatedEvent((User) null);
      User user0 = userCreatedEvent0.getUser();
      assertNull(user0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      User user0 = new User("$~tZ");
      UserCreatedEvent userCreatedEvent0 = new UserCreatedEvent(user0);
      User user1 = userCreatedEvent0.getUser();
      assertSame(user0, user1);
  }
}
