/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 11 13:27:45 GMT 2021
 */

package com.iluwatar.templatemethod;

import org.junit.Test;
import static org.junit.Assert.*;
import com.iluwatar.templatemethod.SubtleMethod;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class SubtleMethod_ESTest extends SubtleMethod_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SubtleMethod subtleMethod0 = new SubtleMethod();
      subtleMethod0.confuseTarget("");
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      SubtleMethod subtleMethod0 = new SubtleMethod();
      subtleMethod0.steal();
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      SubtleMethod subtleMethod0 = new SubtleMethod();
      subtleMethod0.stealTheItem("3U(EnqWU$yeg6O-Iv-U");
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      SubtleMethod subtleMethod0 = new SubtleMethod();
      String string0 = subtleMethod0.pickTarget();
      assertEquals("shop keeper", string0);
  }
}
