/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 11 05:15:02 GMT 2021
 */

package units;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import abstractextensions.UnitExtension;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import units.CommanderUnit;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class CommanderUnit_ESTest extends CommanderUnit_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CommanderUnit commanderUnit0 = new CommanderUnit("CommanderExtension");
      // Undeclared exception!
      try { 
        commanderUnit0.getUnitExtension((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      CommanderUnit commanderUnit0 = new CommanderUnit("CommanderExtension");
      UnitExtension unitExtension0 = commanderUnit0.getUnitExtension("CommanderExtension");
      assertNotNull(unitExtension0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      CommanderUnit commanderUnit0 = new CommanderUnit("units.CommanderUnit");
      UnitExtension unitExtension0 = commanderUnit0.getUnitExtension("units.CommanderUnit");
      assertNull(unitExtension0);
  }
}
