/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 11 08:03:10 GMT 2021
 */

package com.iluwatar.hexagonal.administration;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.iluwatar.hexagonal.administration.ConsoleAdministrationSrvImpl;
import com.iluwatar.hexagonal.banking.WireTransfers;
import com.iluwatar.hexagonal.database.InMemoryTicketRepository;
import com.iluwatar.hexagonal.domain.LotteryAdministration;
import com.iluwatar.hexagonal.eventlog.StdOutEventLog;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;
import org.slf4j.Logger;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class ConsoleAdministrationSrvImpl_ESTest extends ConsoleAdministrationSrvImpl_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ConsoleAdministrationSrvImpl consoleAdministrationSrvImpl0 = new ConsoleAdministrationSrvImpl((LotteryAdministration) null, (Logger) null);
      // Undeclared exception!
      try { 
        consoleAdministrationSrvImpl0.resetLottery();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Cannot invoke \"com.iluwatar.hexagonal.domain.LotteryAdministration.resetLottery()\" because \"this.administration\" is null
         //
         verifyException("com.iluwatar.hexagonal.administration.ConsoleAdministrationSrvImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      InMemoryTicketRepository inMemoryTicketRepository0 = new InMemoryTicketRepository();
      StdOutEventLog stdOutEventLog0 = new StdOutEventLog();
      LotteryAdministration lotteryAdministration0 = new LotteryAdministration(inMemoryTicketRepository0, stdOutEventLog0, (WireTransfers) null);
      Logger logger0 = mock(Logger.class, new ViolatedAssumptionAnswer());
      ConsoleAdministrationSrvImpl consoleAdministrationSrvImpl0 = new ConsoleAdministrationSrvImpl(lotteryAdministration0, logger0);
      // Undeclared exception!
      consoleAdministrationSrvImpl0.performLottery();
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ConsoleAdministrationSrvImpl consoleAdministrationSrvImpl0 = new ConsoleAdministrationSrvImpl((LotteryAdministration) null, (Logger) null);
      // Undeclared exception!
      try { 
        consoleAdministrationSrvImpl0.getAllSubmittedTickets();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Cannot invoke \"com.iluwatar.hexagonal.domain.LotteryAdministration.getAllSubmittedTickets()\" because \"this.administration\" is null
         //
         verifyException("com.iluwatar.hexagonal.administration.ConsoleAdministrationSrvImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      InMemoryTicketRepository inMemoryTicketRepository0 = new InMemoryTicketRepository();
      StdOutEventLog stdOutEventLog0 = new StdOutEventLog();
      LotteryAdministration lotteryAdministration0 = new LotteryAdministration(inMemoryTicketRepository0, stdOutEventLog0, (WireTransfers) null);
      Logger logger0 = mock(Logger.class, new ViolatedAssumptionAnswer());
      ConsoleAdministrationSrvImpl consoleAdministrationSrvImpl0 = new ConsoleAdministrationSrvImpl(lotteryAdministration0, logger0);
      consoleAdministrationSrvImpl0.getAllSubmittedTickets();
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      InMemoryTicketRepository inMemoryTicketRepository0 = new InMemoryTicketRepository();
      StdOutEventLog stdOutEventLog0 = new StdOutEventLog();
      LotteryAdministration lotteryAdministration0 = new LotteryAdministration(inMemoryTicketRepository0, stdOutEventLog0, (WireTransfers) null);
      Logger logger0 = mock(Logger.class, new ViolatedAssumptionAnswer());
      ConsoleAdministrationSrvImpl consoleAdministrationSrvImpl0 = new ConsoleAdministrationSrvImpl(lotteryAdministration0, logger0);
      consoleAdministrationSrvImpl0.resetLottery();
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      ConsoleAdministrationSrvImpl consoleAdministrationSrvImpl0 = new ConsoleAdministrationSrvImpl((LotteryAdministration) null, (Logger) null);
      // Undeclared exception!
      try { 
        consoleAdministrationSrvImpl0.performLottery();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Cannot invoke \"com.iluwatar.hexagonal.domain.LotteryAdministration.performLottery()\" because \"this.administration\" is null
         //
         verifyException("com.iluwatar.hexagonal.administration.ConsoleAdministrationSrvImpl", e);
      }
  }
}
