/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 11 05:50:04 GMT 2021
 */

package com.iluwatar.flux.action;

import org.junit.Test;
import static org.junit.Assert.*;
import com.iluwatar.flux.action.Content;
import com.iluwatar.flux.action.ContentAction;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class ContentAction_ESTest extends ContentAction_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Content content0 = Content.PRODUCTS;
      ContentAction contentAction0 = new ContentAction(content0);
      Content content1 = contentAction0.getContent();
      assertEquals("Products - This page lists the company's products.", content1.toString());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ContentAction contentAction0 = new ContentAction((Content) null);
      contentAction0.getContent();
  }
}
