/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 11 06:00:16 GMT 2021
 */

package com.iluwatar.front.controller;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.iluwatar.front.controller.FrontController;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class FrontController_ESTest extends FrontController_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      FrontController frontController0 = new FrontController();
      frontController0.handleRequest((String) null);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      FrontController frontController0 = new FrontController();
      // Undeclared exception!
      try { 
        frontController0.handleRequest("");
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // java.lang.InstantiationException: com.iluwatar.front.controller.Command
         //
         verifyException("com.iluwatar.front.controller.FrontController", e);
      }
  }
}
