/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 11 08:41:34 GMT 2021
 */

package com.iluwatar.interpreter;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.iluwatar.interpreter.NumberExpression;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class NumberExpression_ESTest extends NumberExpression_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      NumberExpression numberExpression0 = new NumberExpression(0);
      int int0 = numberExpression0.interpret();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      NumberExpression numberExpression0 = new NumberExpression((-1));
      int int0 = numberExpression0.interpret();
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      NumberExpression numberExpression0 = null;
      try {
        numberExpression0 = new NumberExpression((String) null);
        fail("Expecting exception: NumberFormatException");
      
      } catch(NumberFormatException e) {
         //
         // null
         //
         verifyException("java.lang.Integer", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      NumberExpression numberExpression0 = new NumberExpression("7");
      String string0 = numberExpression0.toString();
      assertEquals("number", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      NumberExpression numberExpression0 = new NumberExpression("7");
      int int0 = numberExpression0.interpret();
      assertEquals(7, int0);
  }
}
