/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 11 08:42:41 GMT 2021
 */

package com.iluwatar.interpreter;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.iluwatar.interpreter.Expression;
import com.iluwatar.interpreter.MultiplyExpression;
import com.iluwatar.interpreter.NumberExpression;
import com.iluwatar.interpreter.PlusExpression;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class PlusExpression_ESTest extends PlusExpression_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      MultiplyExpression multiplyExpression0 = new MultiplyExpression((Expression) null, (Expression) null);
      PlusExpression plusExpression0 = new PlusExpression((Expression) null, multiplyExpression0);
      assertEquals("+", plusExpression0.toString());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      NumberExpression numberExpression0 = new NumberExpression(0);
      PlusExpression plusExpression0 = new PlusExpression(numberExpression0, numberExpression0);
      int int0 = plusExpression0.interpret();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      NumberExpression numberExpression0 = new NumberExpression((-684));
      PlusExpression plusExpression0 = new PlusExpression(numberExpression0, numberExpression0);
      int int0 = plusExpression0.interpret();
      assertEquals((-1368), int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      PlusExpression plusExpression0 = new PlusExpression((Expression) null, (Expression) null);
      // Undeclared exception!
      try { 
        plusExpression0.interpret();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Cannot invoke \"com.iluwatar.interpreter.Expression.interpret()\" because \"this.leftExpression\" is null
         //
         verifyException("com.iluwatar.interpreter.PlusExpression", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      NumberExpression numberExpression0 = new NumberExpression(1387);
      PlusExpression plusExpression0 = new PlusExpression(numberExpression0, numberExpression0);
      int int0 = plusExpression0.interpret();
      assertEquals(2774, int0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      PlusExpression plusExpression0 = new PlusExpression((Expression) null, (Expression) null);
      String string0 = plusExpression0.toString();
      assertEquals("+", string0);
  }
}
