/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 11 03:41:09 GMT 2021
 */

package com.iluwatar.commander.exceptions;

import org.junit.Test;
import static org.junit.Assert.*;
import com.iluwatar.commander.exceptions.DatabaseUnavailableException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class DatabaseUnavailableException_ESTest extends DatabaseUnavailableException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      DatabaseUnavailableException databaseUnavailableException0 = new DatabaseUnavailableException();
  }
}
