/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 11 03:08:12 GMT 2021
 */

package com.iluwatar.callback;

import org.junit.Test;
import static org.junit.Assert.*;
import com.iluwatar.callback.SimpleTask;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class SimpleTask_ESTest extends SimpleTask_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SimpleTask simpleTask0 = new SimpleTask();
      simpleTask0.execute();
  }
}
