/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 11 04:21:49 GMT 2021
 */

package com.iluwatar.data.locality.game.component.manager;

import org.junit.Test;
import static org.junit.Assert.*;
import com.iluwatar.data.locality.game.component.manager.AiComponentManager;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class AiComponentManager_ESTest extends AiComponentManager_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      AiComponentManager aiComponentManager0 = new AiComponentManager(1597);
      aiComponentManager0.update();
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      AiComponentManager aiComponentManager0 = new AiComponentManager(0);
      aiComponentManager0.start();
  }
}
