/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 11 12:41:29 GMT 2021
 */

package com.iluwatar.servicelocator;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.iluwatar.servicelocator.Service;
import com.iluwatar.servicelocator.ServiceCache;
import com.iluwatar.servicelocator.ServiceImpl;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class ServiceCache_ESTest extends ServiceCache_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ServiceCache serviceCache0 = new ServiceCache();
      // Undeclared exception!
      try { 
        serviceCache0.addService((Service) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Cannot invoke \"com.iluwatar.servicelocator.Service.getName()\" because \"newService\" is null
         //
         verifyException("com.iluwatar.servicelocator.ServiceCache", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ServiceCache serviceCache0 = new ServiceCache();
      Service service0 = serviceCache0.getService("TdF>l#}xI");
      assertNull(service0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ServiceCache serviceCache0 = new ServiceCache();
      ServiceImpl serviceImpl0 = new ServiceImpl("");
      serviceCache0.addService(serviceImpl0);
      Service service0 = serviceCache0.getService("");
      assertEquals(1, service0.getId());
  }
}
