/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 11 12:43:42 GMT 2021
 */

package com.iluwatar.servicelocator;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.iluwatar.servicelocator.Service;
import com.iluwatar.servicelocator.ServiceLocator;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class ServiceLocator_ESTest extends ServiceLocator_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Service service0 = ServiceLocator.getService("com.iluwatar.servicelocator.ServiceLocator");
      assertNull(service0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Service service0 = ServiceLocator.getService("jndi/serviceA");
      assertEquals("jndi/serviceA", service0.getName());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      // Undeclared exception!
      try { 
        ServiceLocator.getService((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Cannot invoke \"String.equals(Object)\" because \"serviceName\" is null
         //
         verifyException("com.iluwatar.servicelocator.InitContext", e);
      }
  }
}
