/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 11 05:24:19 GMT 2021
 */

package com.iluwatar.factory;

import org.junit.Test;
import static org.junit.Assert.*;
import com.iluwatar.factory.Car;
import com.iluwatar.factory.CarType;
import java.util.function.Supplier;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class CarType_ESTest extends CarType_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CarType[] carTypeArray0 = CarType.values();
      assertEquals(2, carTypeArray0.length);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      CarType carType0 = CarType.valueOf("FORD");
      assertEquals(CarType.FORD, carType0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      CarType carType0 = CarType.FORD;
      Supplier<Car> supplier0 = carType0.getConstructor();
      assertNotNull(supplier0);
  }
}
