/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 11 05:26:31 GMT 2021
 */

package com.iluwatar.factory;

import org.junit.Test;
import static org.junit.Assert.*;
import com.iluwatar.factory.Ford;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Ford_ESTest extends Ford_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Ford ford0 = new Ford();
      String string0 = ford0.getDescription();
      assertEquals("This is Ford.", string0);
  }
}
