/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 11 08:04:22 GMT 2021
 */

package com.iluwatar.hexagonal.banking;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.iluwatar.hexagonal.banking.InMemoryBank;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class InMemoryBank_ESTest extends InMemoryBank_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      InMemoryBank inMemoryBank0 = new InMemoryBank();
      // Undeclared exception!
      try { 
        inMemoryBank0.transferFunds(0, "", "%sV}hXwp}0.");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Cannot invoke \"java.lang.Integer.intValue()\" because the return value of \"java.util.Map.get(Object)\" is null
         //
         verifyException("com.iluwatar.hexagonal.banking.InMemoryBank", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      InMemoryBank inMemoryBank0 = new InMemoryBank();
      inMemoryBank0.setFunds("", 150000);
      int int0 = inMemoryBank0.getFunds((String) null);
      assertEquals(0, int0);
      
      inMemoryBank0.transferFunds(150000, "Q}pSn;</VD9'S=2_n", "Q}pSn;</VD9'S=2_n");
      inMemoryBank0.setFunds((String) null, 150000);
      inMemoryBank0.setFunds((String) null, 2593);
      inMemoryBank0.getFunds("");
      inMemoryBank0.transferFunds(2387, "", (String) null);
      inMemoryBank0.setFunds("Pjq>R", 0);
      int int1 = inMemoryBank0.getFunds("Pjq>R");
      assertEquals(0, int1);
  }
}
