/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 11 13:17:55 GMT 2021
 */

package com.iluwatar.state;

import org.junit.Test;
import static org.junit.Assert.*;
import com.iluwatar.state.AngryState;
import com.iluwatar.state.Mammoth;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class AngryState_ESTest extends AngryState_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Mammoth mammoth0 = new Mammoth();
      AngryState angryState0 = new AngryState(mammoth0);
      angryState0.observe();
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Mammoth mammoth0 = new Mammoth();
      AngryState angryState0 = new AngryState(mammoth0);
      angryState0.onEnterState();
  }
}
