/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 11 13:19:07 GMT 2021
 */

package com.iluwatar.state;

import org.junit.Test;
import static org.junit.Assert.*;
import com.iluwatar.state.Mammoth;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Mammoth_ESTest extends Mammoth_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Mammoth mammoth0 = new Mammoth();
      mammoth0.observe();
      assertEquals("The mammoth", mammoth0.toString());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Mammoth mammoth0 = new Mammoth();
      mammoth0.timePasses();
      mammoth0.timePasses();
      assertEquals("The mammoth", mammoth0.toString());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Mammoth mammoth0 = new Mammoth();
      String string0 = mammoth0.toString();
      assertEquals("The mammoth", string0);
  }
}
