/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 11 13:19:12 GMT 2021
 */

package com.iluwatar.state;

import org.junit.Test;
import static org.junit.Assert.*;
import com.iluwatar.state.Mammoth;
import com.iluwatar.state.PeacefulState;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class PeacefulState_ESTest extends PeacefulState_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      PeacefulState peacefulState0 = new PeacefulState((Mammoth) null);
      peacefulState0.onEnterState();
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Mammoth mammoth0 = new Mammoth();
      PeacefulState peacefulState0 = new PeacefulState(mammoth0);
      peacefulState0.observe();
  }
}
