/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 11 14:11:17 GMT 2021
 */

package com.iluwatar.visitor;

import org.junit.Test;
import static org.junit.Assert.*;
import com.iluwatar.visitor.Commander;
import com.iluwatar.visitor.Sergeant;
import com.iluwatar.visitor.Soldier;
import com.iluwatar.visitor.SoldierVisitor;
import com.iluwatar.visitor.Unit;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class SoldierVisitor_ESTest extends SoldierVisitor_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SoldierVisitor soldierVisitor0 = new SoldierVisitor();
      soldierVisitor0.visitCommander((Commander) null);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      SoldierVisitor soldierVisitor0 = new SoldierVisitor();
      soldierVisitor0.visitSergeant((Sergeant) null);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      SoldierVisitor soldierVisitor0 = new SoldierVisitor();
      Soldier soldier0 = new Soldier((Unit[]) null);
      soldierVisitor0.visitSoldier(soldier0);
      assertEquals("soldier", soldier0.toString());
  }
}
