/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 11 12:13:50 GMT 2021
 */

package com.iluwatar.saga.orchestration;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.iluwatar.saga.orchestration.ChapterResult;
import com.iluwatar.saga.orchestration.HotelBookingService;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class HotelBookingService_ESTest extends HotelBookingService_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      HotelBookingService hotelBookingService0 = new HotelBookingService();
      String string0 = hotelBookingService0.getName();
      assertEquals("booking a Hotel", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      HotelBookingService hotelBookingService0 = new HotelBookingService();
      // Undeclared exception!
      try { 
        hotelBookingService0.rollback((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      HotelBookingService hotelBookingService0 = new HotelBookingService();
      ChapterResult<String> chapterResult0 = hotelBookingService0.rollback("crashed_order");
      assertEquals("booking a Hotel", hotelBookingService0.getName());
      assertFalse(chapterResult0.isSuccess());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      HotelBookingService hotelBookingService0 = new HotelBookingService();
      ChapterResult<String> chapterResult0 = hotelBookingService0.rollback("");
      assertTrue(chapterResult0.isSuccess());
      assertEquals("booking a Hotel", hotelBookingService0.getName());
  }
}
