/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 11 03:06:59 GMT 2021
 */

package com.iluwatar.caching;

import org.junit.Test;
import static org.junit.Assert.*;
import com.iluwatar.caching.UserAccount;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class UserAccount_ESTest extends UserAccount_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      UserAccount userAccount0 = new UserAccount("5;mRU8YJ1ix)", (String) null, "com.iluwatar.caching.UserAccount");
      userAccount0.getUserName();
      assertEquals("5;mRU8YJ1ix), null, com.iluwatar.caching.UserAccount", userAccount0.toString());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      UserAccount userAccount0 = new UserAccount("", "8er_A>>9Z%Z", "8er_A>>9Z%Z");
      userAccount0.getUserId();
      assertEquals(", 8er_A>>9Z%Z, 8er_A>>9Z%Z", userAccount0.toString());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      UserAccount userAccount0 = new UserAccount("5;mRU8YJ1ix)", (String) null, "com.iluwatar.caching.UserAccount");
      assertEquals("5;mRU8YJ1ix), null, com.iluwatar.caching.UserAccount", userAccount0.toString());
      
      userAccount0.setAdditionalInfo((String) null);
      userAccount0.getAdditionalInfo();
      assertEquals("5;mRU8YJ1ix), null, null", userAccount0.toString());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      UserAccount userAccount0 = new UserAccount("", "8er_A>>9Z%Z", "8er_A>>9Z%Z");
      assertEquals("8er_A>>9Z%Z", userAccount0.getAdditionalInfo());
      
      userAccount0.setAdditionalInfo("");
      userAccount0.getAdditionalInfo();
      assertEquals(", 8er_A>>9Z%Z, ", userAccount0.toString());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      UserAccount userAccount0 = new UserAccount("", "8er_A>>9Z%Z", "8er_A>>9Z%Z");
      String string0 = userAccount0.toString();
      assertEquals(", 8er_A>>9Z%Z, 8er_A>>9Z%Z", string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      UserAccount userAccount0 = new UserAccount("", "8er_A>>9Z%Z", "8er_A>>9Z%Z");
      assertEquals("8er_A>>9Z%Z", userAccount0.getUserName());
      
      userAccount0.setUserName("");
      userAccount0.getUserName();
      assertEquals(", , 8er_A>>9Z%Z", userAccount0.toString());
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      UserAccount userAccount0 = new UserAccount("", "8er_A>>9Z%Z", "8er_A>>9Z%Z");
      userAccount0.getUserName();
      assertEquals(", 8er_A>>9Z%Z, 8er_A>>9Z%Z", userAccount0.toString());
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      UserAccount userAccount0 = new UserAccount("", "8er_A>>9Z%Z", "8er_A>>9Z%Z");
      userAccount0.getAdditionalInfo();
      assertEquals(", 8er_A>>9Z%Z, 8er_A>>9Z%Z", userAccount0.toString());
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      UserAccount userAccount0 = new UserAccount("", "8er_A>>9Z%Z", "8er_A>>9Z%Z");
      userAccount0.setUserId((String) null);
      userAccount0.getUserId();
      assertEquals("null, 8er_A>>9Z%Z, 8er_A>>9Z%Z", userAccount0.toString());
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      UserAccount userAccount0 = new UserAccount("sa?2W2r`QCPO'", "sa?2W2r`QCPO'", "sa?2W2r`QCPO'");
      String string0 = userAccount0.getUserId();
      assertEquals("sa?2W2r`QCPO'", string0);
  }
}
