/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 11 13:17:30 GMT 2021
 */

package com.iluwatar.specification.selector;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.iluwatar.specification.creature.Creature;
import com.iluwatar.specification.creature.Dragon;
import com.iluwatar.specification.creature.Goblin;
import com.iluwatar.specification.selector.MassSmallerThanOrEqSelector;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class MassSmallerThanOrEqSelector_ESTest extends MassSmallerThanOrEqSelector_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      MassSmallerThanOrEqSelector massSmallerThanOrEqSelector0 = new MassSmallerThanOrEqSelector(0.0);
      Dragon dragon0 = new Dragon();
      boolean boolean0 = massSmallerThanOrEqSelector0.test((Creature) dragon0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      MassSmallerThanOrEqSelector massSmallerThanOrEqSelector0 = new MassSmallerThanOrEqSelector(478.363167);
      // Undeclared exception!
      try { 
        massSmallerThanOrEqSelector0.test((Creature) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Cannot invoke \"com.iluwatar.specification.creature.Creature.getMass()\" because \"t\" is null
         //
         verifyException("com.iluwatar.specification.selector.MassSmallerThanOrEqSelector", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      MassSmallerThanOrEqSelector massSmallerThanOrEqSelector0 = new MassSmallerThanOrEqSelector(861.6044);
      Goblin goblin0 = new Goblin();
      boolean boolean0 = massSmallerThanOrEqSelector0.test((Creature) goblin0);
      assertTrue(boolean0);
  }
}
