/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 11 13:14:39 GMT 2021
 */

package com.iluwatar.specification.property;

import org.junit.Test;
import static org.junit.Assert.*;
import com.iluwatar.specification.property.Movement;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Movement_ESTest extends Movement_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Movement[] movementArray0 = Movement.values();
      assertEquals(3, movementArray0.length);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Movement movement0 = Movement.valueOf("WALKING");
      String string0 = movement0.toString();
      assertEquals("walking", string0);
  }
}
