/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 11 08:23:08 GMT 2021
 */

package com.iluwatar.intercepting.filter;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.iluwatar.intercepting.filter.AddressFilter;
import com.iluwatar.intercepting.filter.Order;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class AddressFilter_ESTest extends AddressFilter_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      AddressFilter addressFilter0 = new AddressFilter();
      // Undeclared exception!
      try { 
        addressFilter0.execute((Order) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Cannot invoke \"com.iluwatar.intercepting.filter.Order.getAddress()\" because \"order\" is null
         //
         verifyException("com.iluwatar.intercepting.filter.AddressFilter", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      AddressFilter addressFilter0 = new AddressFilter();
      Order order0 = new Order((String) null, "", "", (String) null, (String) null);
      String string0 = addressFilter0.execute(order0);
      assertEquals("Invalid address! ", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      AddressFilter addressFilter0 = new AddressFilter();
      Order order0 = new Order("com.iluwatar.intercepting.filter.NameFilter", "com.iluwatar.intercepting.filter.NameFilter", "NoRCQwvg/.E", "JgOQ1bJMgIg6~d", "JgOQ1bJMgIg6~d");
      String string0 = addressFilter0.execute(order0);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      AddressFilter addressFilter0 = new AddressFilter();
      Order order0 = new Order();
      String string0 = addressFilter0.execute(order0);
      assertEquals("Invalid address! ", string0);
  }
}
