/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 11 08:29:05 GMT 2021
 */

package com.iluwatar.intercepting.filter;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.iluwatar.intercepting.filter.DepositFilter;
import com.iluwatar.intercepting.filter.Order;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class DepositFilter_ESTest extends DepositFilter_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      DepositFilter depositFilter0 = new DepositFilter();
      // Undeclared exception!
      try { 
        depositFilter0.execute((Order) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Cannot invoke \"com.iluwatar.intercepting.filter.Order.getDepositNumber()\" because \"order\" is null
         //
         verifyException("com.iluwatar.intercepting.filter.DepositFilter", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      DepositFilter depositFilter0 = new DepositFilter();
      Order order0 = new Order("#idG)t1", "#idG)t1", "r.={aYo)Yny@'])0:", "", "");
      String string0 = depositFilter0.execute(order0);
      assertEquals("Invalid deposit number! ", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      DepositFilter depositFilter0 = new DepositFilter();
      Order order0 = new Order("*mD8", "com.iluwatar.intercepting.filter.AddressFilter", "", "*mD8", "*mD8");
      String string0 = depositFilter0.execute(order0);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      DepositFilter depositFilter0 = new DepositFilter();
      Order order0 = new Order();
      String string0 = depositFilter0.execute(order0);
      assertEquals("Invalid deposit number! ", string0);
  }
}
