/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 11 08:33:00 GMT 2021
 */

package com.iluwatar.intercepting.filter;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.iluwatar.intercepting.filter.NameFilter;
import com.iluwatar.intercepting.filter.Order;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class NameFilter_ESTest extends NameFilter_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      NameFilter nameFilter0 = new NameFilter();
      // Undeclared exception!
      try { 
        nameFilter0.execute((Order) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Cannot invoke \"com.iluwatar.intercepting.filter.Order.getName()\" because \"order\" is null
         //
         verifyException("com.iluwatar.intercepting.filter.NameFilter", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      NameFilter nameFilter0 = new NameFilter();
      Order order0 = new Order();
      order0.setName("`.;w_p*Ws>`6!");
      String string0 = nameFilter0.execute(order0);
      assertEquals("Invalid name! ", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      NameFilter nameFilter0 = new NameFilter();
      Order order0 = new Order("", "r<5", "", "", "r<5");
      String string0 = nameFilter0.execute(order0);
      assertEquals("Invalid name! ", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      NameFilter nameFilter0 = new NameFilter();
      Order order0 = new Order("com.iluwatar.intercepting.filter.NameFilter", (String) null, (String) null, "com.iluwatar.intercepting.filter.NameFilter", "]yv7y03Q*S");
      String string0 = nameFilter0.execute(order0);
      //  // Unstable assertion: assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      NameFilter nameFilter0 = new NameFilter();
      Order order0 = new Order();
      String string0 = nameFilter0.execute(order0);
      assertEquals("Invalid name! ", string0);
  }
}
