/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 11 09:47:23 GMT 2021
 */

package com.iluwatar.model.view.controller;

import org.junit.Test;
import static org.junit.Assert.*;
import com.iluwatar.model.view.controller.Fatigue;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Fatigue_ESTest extends Fatigue_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Fatigue[] fatigueArray0 = Fatigue.values();
      assertEquals(3, fatigueArray0.length);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Fatigue fatigue0 = Fatigue.valueOf("TIRED");
      assertEquals("tired", fatigue0.toString());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Fatigue fatigue0 = Fatigue.SLEEPING;
      String string0 = fatigue0.toString();
      assertEquals("sleeping", string0);
  }
}
