/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 11 09:49:44 GMT 2021
 */

package com.iluwatar.model.view.controller;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.iluwatar.model.view.controller.Fatigue;
import com.iluwatar.model.view.controller.GiantModel;
import com.iluwatar.model.view.controller.GiantView;
import com.iluwatar.model.view.controller.Health;
import com.iluwatar.model.view.controller.Nourishment;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class GiantView_ESTest extends GiantView_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      GiantView giantView0 = new GiantView();
      // Undeclared exception!
      try { 
        giantView0.displayGiant((GiantModel) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Cannot invoke \"com.iluwatar.model.view.controller.GiantModel.toString()\" because \"giant\" is null
         //
         verifyException("com.iluwatar.model.view.controller.GiantView", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      GiantView giantView0 = new GiantView();
      Health health0 = Health.WOUNDED;
      Fatigue fatigue0 = Fatigue.ALERT;
      Nourishment nourishment0 = Nourishment.SATURATED;
      GiantModel giantModel0 = new GiantModel(health0, fatigue0, nourishment0);
      giantView0.displayGiant(giantModel0);
      assertEquals(Nourishment.SATURATED, giantModel0.getNourishment());
  }
}
