/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 11 09:50:50 GMT 2021
 */

package com.iluwatar.model.view.controller;

import org.junit.Test;
import static org.junit.Assert.*;
import com.iluwatar.model.view.controller.Health;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Health_ESTest extends Health_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Health[] healthArray0 = Health.values();
      assertEquals(3, healthArray0.length);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Health health0 = Health.valueOf("HEALTHY");
      assertEquals(Health.HEALTHY, health0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Health health0 = Health.DEAD;
      String string0 = health0.toString();
      assertEquals("dead", string0);
  }
}
