/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 11 05:31:18 GMT 2021
 */

package com.iluwatar.factory.method;

import org.junit.Test;
import static org.junit.Assert.*;
import com.iluwatar.factory.method.ElfBlacksmith;
import com.iluwatar.factory.method.ElfWeapon;
import com.iluwatar.factory.method.Weapon;
import com.iluwatar.factory.method.WeaponType;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class ElfBlacksmith_ESTest extends ElfBlacksmith_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ElfBlacksmith elfBlacksmith0 = new ElfBlacksmith();
      Weapon weapon0 = elfBlacksmith0.manufactureWeapon((WeaponType) null);
      assertNull(weapon0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ElfBlacksmith elfBlacksmith0 = new ElfBlacksmith();
      WeaponType weaponType0 = WeaponType.UNDEFINED;
      ElfWeapon elfWeapon0 = (ElfWeapon)elfBlacksmith0.manufactureWeapon(weaponType0);
      assertEquals("Elven ", elfWeapon0.toString());
  }
}
