/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 11 04:22:05 GMT 2021
 */

package com.iluwatar.data.locality.game.component;

import org.junit.Test;
import static org.junit.Assert.*;
import com.iluwatar.data.locality.game.component.PhysicsComponent;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class PhysicsComponent_ESTest extends PhysicsComponent_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      PhysicsComponent physicsComponent0 = new PhysicsComponent();
      physicsComponent0.update();
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      PhysicsComponent physicsComponent0 = new PhysicsComponent();
      physicsComponent0.render();
  }
}
