/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 11 05:01:28 GMT 2021
 */

package com.iluwatar.event.asynchronous;

import org.junit.Test;
import static org.junit.Assert.*;
import com.iluwatar.event.asynchronous.InvalidOperationException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class InvalidOperationException_ESTest extends InvalidOperationException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      InvalidOperationException invalidOperationException0 = new InvalidOperationException("");
  }
}
