/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 11 09:07:56 GMT 2021
 */

package com.iluwatar.leaderelection.ring;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.iluwatar.leaderelection.Instance;
import com.iluwatar.leaderelection.bully.BullyInstance;
import com.iluwatar.leaderelection.bully.BullyMessageManager;
import com.iluwatar.leaderelection.ring.RingInstance;
import com.iluwatar.leaderelection.ring.RingMessageManager;
import java.util.HashMap;
import java.util.Map;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class RingMessageManager_ESTest extends RingMessageManager_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      HashMap<Integer, Instance> hashMap0 = new HashMap<Integer, Instance>();
      Integer integer0 = new Integer(0);
      BullyMessageManager bullyMessageManager0 = new BullyMessageManager(hashMap0);
      RingInstance ringInstance0 = new RingInstance(bullyMessageManager0, 2127, 2127);
      hashMap0.put(integer0, ringInstance0);
      RingMessageManager ringMessageManager0 = new RingMessageManager(hashMap0);
      boolean boolean0 = ringMessageManager0.sendLeaderMessage(0, (-1632));
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      HashMap<Integer, Instance> hashMap0 = new HashMap<Integer, Instance>();
      RingMessageManager ringMessageManager0 = new RingMessageManager(hashMap0);
      // Undeclared exception!
      try { 
        ringMessageManager0.sendLeaderMessage(0, (-1632));
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      HashMap<Integer, Instance> hashMap0 = new HashMap<Integer, Instance>();
      Integer integer0 = new Integer(0);
      BullyMessageManager bullyMessageManager0 = new BullyMessageManager(hashMap0);
      RingInstance ringInstance0 = new RingInstance(bullyMessageManager0, 2127, 2127);
      hashMap0.put(integer0, ringInstance0);
      RingMessageManager ringMessageManager0 = new RingMessageManager(hashMap0);
      ringMessageManager0.sendHeartbeatInvokeMessage(0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      HashMap<Integer, Instance> hashMap0 = new HashMap<Integer, Instance>();
      RingMessageManager ringMessageManager0 = new RingMessageManager(hashMap0);
      Integer integer0 = new Integer(0);
      RingInstance ringInstance0 = new RingInstance(ringMessageManager0, (-1), 0);
      hashMap0.put(integer0, ringInstance0);
      boolean boolean0 = ringMessageManager0.sendHeartbeatMessage(0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      HashMap<Integer, Instance> hashMap0 = new HashMap<Integer, Instance>();
      RingMessageManager ringMessageManager0 = new RingMessageManager(hashMap0);
      Integer integer0 = new Integer(0);
      BullyInstance bullyInstance0 = new BullyInstance(ringMessageManager0, 1949, 0);
      bullyInstance0.setAlive(false);
      hashMap0.put(integer0, bullyInstance0);
      boolean boolean0 = ringMessageManager0.sendHeartbeatMessage(0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      HashMap<Integer, Instance> hashMap0 = new HashMap<Integer, Instance>();
      RingMessageManager ringMessageManager0 = new RingMessageManager(hashMap0);
      Integer integer0 = new Integer(1);
      RingInstance ringInstance0 = new RingInstance(ringMessageManager0, (-1), 0);
      hashMap0.put(integer0, ringInstance0);
      boolean boolean0 = ringMessageManager0.sendElectionMessage(0, (String) null);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      RingMessageManager ringMessageManager0 = new RingMessageManager((Map<Integer, Instance>) null);
      // Undeclared exception!
      try { 
        ringMessageManager0.sendLeaderMessage(99, 99);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Cannot invoke \"java.util.Map.keySet()\" because \"this.instanceMap\" is null
         //
         verifyException("com.iluwatar.leaderelection.AbstractMessageManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      HashMap<Integer, Instance> hashMap0 = new HashMap<Integer, Instance>();
      RingMessageManager ringMessageManager0 = new RingMessageManager(hashMap0);
      // Undeclared exception!
      try { 
        ringMessageManager0.sendHeartbeatInvokeMessage((-3488));
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      HashMap<Integer, Instance> hashMap0 = new HashMap<Integer, Instance>();
      RingMessageManager ringMessageManager0 = new RingMessageManager(hashMap0);
      // Undeclared exception!
      try { 
        ringMessageManager0.sendElectionMessage((-558), "");
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      HashMap<Integer, Instance> hashMap0 = new HashMap<Integer, Instance>();
      RingMessageManager ringMessageManager0 = new RingMessageManager(hashMap0);
      // Undeclared exception!
      try { 
        ringMessageManager0.sendHeartbeatMessage((-441));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Cannot invoke \"com.iluwatar.leaderelection.Instance.isAlive()\" because \"leaderInstance\" is null
         //
         verifyException("com.iluwatar.leaderelection.ring.RingMessageManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      RingMessageManager ringMessageManager0 = new RingMessageManager((Map<Integer, Instance>) null);
      // Undeclared exception!
      try { 
        ringMessageManager0.sendHeartbeatInvokeMessage(0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Cannot invoke \"java.util.Map.keySet()\" because \"this.instanceMap\" is null
         //
         verifyException("com.iluwatar.leaderelection.AbstractMessageManager", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      RingMessageManager ringMessageManager0 = new RingMessageManager((Map<Integer, Instance>) null);
      // Undeclared exception!
      try { 
        ringMessageManager0.sendElectionMessage((-735), "c");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Cannot invoke \"java.util.Map.keySet()\" because \"this.instanceMap\" is null
         //
         verifyException("com.iluwatar.leaderelection.AbstractMessageManager", e);
      }
  }
}
