/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 11 10:23:16 GMT 2021
 */

package com.iluwatar.observer;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.iluwatar.observer.Hobbits;
import com.iluwatar.observer.Weather;
import com.iluwatar.observer.WeatherObserver;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Weather_ESTest extends Weather_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Weather weather0 = new Weather();
      weather0.addObserver((WeatherObserver) null);
      // Undeclared exception!
      try { 
        weather0.timePasses();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Cannot invoke \"com.iluwatar.observer.WeatherObserver.update(com.iluwatar.observer.WeatherType)\" because \"obs\" is null
         //
         verifyException("com.iluwatar.observer.Weather", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Weather weather0 = new Weather();
      Hobbits hobbits0 = new Hobbits();
      weather0.removeObserver(hobbits0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Weather weather0 = new Weather();
      Hobbits hobbits0 = new Hobbits();
      weather0.addObserver(hobbits0);
      weather0.timePasses();
  }
}
