/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 11 02:14:18 GMT 2021
 */

package com.iluwatar.abstractfactory;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.iluwatar.abstractfactory.App;
import com.iluwatar.abstractfactory.Kingdom;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class App_ESTest extends App_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      App app0 = new App();
      // Undeclared exception!
      try { 
        app0.createKingdom((Kingdom.FactoryMaker.KingdomType) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Cannot invoke \"com.iluwatar.abstractfactory.Kingdom$FactoryMaker$KingdomType.ordinal()\" because \"type\" is null
         //
         verifyException("com.iluwatar.abstractfactory.Kingdom$FactoryMaker", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      App app0 = new App();
      app0.run();
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      App app0 = new App();
      Kingdom.FactoryMaker.KingdomType kingdom_FactoryMaker_KingdomType0 = Kingdom.FactoryMaker.KingdomType.ELF;
      app0.createKingdom(kingdom_FactoryMaker_KingdomType0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      String[] stringArray0 = new String[3];
      App.main(stringArray0);
      assertEquals(3, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      App app0 = new App();
      Kingdom kingdom0 = app0.getKingdom();
      assertNotNull(kingdom0);
  }
}
