/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 11 02:22:03 GMT 2021
 */

package com.iluwatar.abstractfactory;

import org.junit.Test;
import static org.junit.Assert.*;
import com.iluwatar.abstractfactory.OrcCastle;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class OrcCastle_ESTest extends OrcCastle_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      OrcCastle orcCastle0 = new OrcCastle();
      String string0 = orcCastle0.getDescription();
      assertEquals("This is the Orc castle!", string0);
  }
}
