/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 11 02:24:16 GMT 2021
 */

package com.iluwatar.abstractfactory;

import org.junit.Test;
import static org.junit.Assert.*;
import com.iluwatar.abstractfactory.Army;
import com.iluwatar.abstractfactory.Castle;
import com.iluwatar.abstractfactory.King;
import com.iluwatar.abstractfactory.OrcKingdomFactory;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class OrcKingdomFactory_ESTest extends OrcKingdomFactory_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      OrcKingdomFactory orcKingdomFactory0 = new OrcKingdomFactory();
      King king0 = orcKingdomFactory0.createKing();
      assertEquals("This is the Orc king!", king0.getDescription());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      OrcKingdomFactory orcKingdomFactory0 = new OrcKingdomFactory();
      Army army0 = orcKingdomFactory0.createArmy();
      assertEquals("This is the Orc Army!", army0.getDescription());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      OrcKingdomFactory orcKingdomFactory0 = new OrcKingdomFactory();
      Castle castle0 = orcKingdomFactory0.createCastle();
      assertEquals("This is the Orc castle!", castle0.getDescription());
  }
}
