/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 11 11:45:19 GMT 2021
 */

package com.iluwatar.reader.writer.lock;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.iluwatar.reader.writer.lock.Reader;
import java.util.concurrent.locks.Lock;
import java.util.concurrent.locks.ReentrantLock;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Reader_ESTest extends Reader_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ReentrantLock reentrantLock0 = new ReentrantLock(false);
      Reader reader0 = new Reader("._OWoXx7?bX3\"O", reentrantLock0, (-1942L));
      // Undeclared exception!
      try { 
        reader0.run();
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // timeout value is negative
         //
         verifyException("java.lang.Thread", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ReentrantLock reentrantLock0 = new ReentrantLock();
      Reader reader0 = new Reader("InterruptedException when reading", reentrantLock0, (-1L));
      // Undeclared exception!
      try { 
        reader0.read();
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // timeout value is negative
         //
         verifyException("java.lang.Thread", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ReentrantLock reentrantLock0 = new ReentrantLock();
      Reader reader0 = new Reader("", reentrantLock0);
      reader0.read();
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ReentrantLock reentrantLock0 = new ReentrantLock();
      Reader reader0 = new Reader("})|7/}", reentrantLock0);
      reader0.run();
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Reader reader0 = new Reader("})|7/}", (Lock) null);
      // Undeclared exception!
      try { 
        reader0.run();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Cannot invoke \"java.util.concurrent.locks.Lock.lock()\" because \"this.readLock\" is null
         //
         verifyException("com.iluwatar.reader.writer.lock.Reader", e);
      }
  }
}
