/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 11 09:13:09 GMT 2021
 */

package com.iluwatar.leaderfollowers;

import org.junit.Test;
import static org.junit.Assert.*;
import com.iluwatar.leaderfollowers.App;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class App_ESTest extends App_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      App app0 = new App();
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      String[] stringArray0 = new String[5];
      App.main(stringArray0);
      assertEquals(5, stringArray0.length);
  }
}
