/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 11 11:26:02 GMT 2021
 */

package com.iluwatar.queue.load.leveling;

import org.junit.Test;
import static org.junit.Assert.*;
import com.iluwatar.queue.load.leveling.Message;
import com.iluwatar.queue.load.leveling.MessageQueue;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class MessageQueue_ESTest extends MessageQueue_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      MessageQueue messageQueue0 = new MessageQueue();
      Message message0 = new Message("");
      messageQueue0.submitMsg(message0);
      Message message1 = messageQueue0.retrieveMsg();
      assertEquals("", message1.getMsg());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      MessageQueue messageQueue0 = new MessageQueue();
      messageQueue0.submitMsg((Message) null);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      MessageQueue messageQueue0 = new MessageQueue();
      Message message0 = messageQueue0.retrieveMsg();
      assertNull(message0);
  }
}
