/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 11 11:29:43 GMT 2021
 */

package com.iluwatar.queue.load.leveling;

import org.junit.Test;
import static org.junit.Assert.*;
import com.iluwatar.queue.load.leveling.Message;
import com.iluwatar.queue.load.leveling.MessageQueue;
import com.iluwatar.queue.load.leveling.TaskGenerator;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class TaskGenerator_ESTest extends TaskGenerator_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      TaskGenerator taskGenerator0 = new TaskGenerator((MessageQueue) null, (-1));
      taskGenerator0.run();
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      TaskGenerator taskGenerator0 = new TaskGenerator((MessageQueue) null, (-1));
      Message message0 = new Message("com.iluwatar.queue.load.leveling.App");
      taskGenerator0.submit(message0);
      assertEquals("com.iluwatar.queue.load.leveling.App", message0.toString());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      MessageQueue messageQueue0 = new MessageQueue();
      TaskGenerator taskGenerator0 = new TaskGenerator(messageQueue0, 1);
      Message message0 = new Message("com.iluwatar.queue.load.leveling.Message");
      taskGenerator0.submit(message0);
      assertEquals("com.iluwatar.queue.load.leveling.Message", message0.toString());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      MessageQueue messageQueue0 = new MessageQueue();
      TaskGenerator taskGenerator0 = new TaskGenerator(messageQueue0, 1);
      taskGenerator0.run();
  }
}
