/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 11 12:53:58 GMT 2021
 */

package com.iluwatar.singleton;

import org.junit.Test;
import static org.junit.Assert.*;
import com.iluwatar.singleton.IvoryTower;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class IvoryTower_ESTest extends IvoryTower_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      IvoryTower ivoryTower0 = IvoryTower.getInstance();
      assertNotNull(ivoryTower0);
  }
}
