/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 11 12:56:10 GMT 2021
 */

package com.iluwatar.singleton;

import org.junit.Test;
import static org.junit.Assert.*;
import com.iluwatar.singleton.ThreadSafeLazyLoadedIvoryTower;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class ThreadSafeLazyLoadedIvoryTower_ESTest extends ThreadSafeLazyLoadedIvoryTower_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ThreadSafeLazyLoadedIvoryTower threadSafeLazyLoadedIvoryTower0 = ThreadSafeLazyLoadedIvoryTower.getInstance();
      ThreadSafeLazyLoadedIvoryTower threadSafeLazyLoadedIvoryTower1 = ThreadSafeLazyLoadedIvoryTower.getInstance();
      assertSame(threadSafeLazyLoadedIvoryTower1, threadSafeLazyLoadedIvoryTower0);
  }
}
