/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 11 12:00:21 GMT 2021
 */

package com.iluwatar.roleobject;

import org.junit.Test;
import static org.junit.Assert.*;
import com.iluwatar.roleobject.BorrowerRole;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class CustomerRole_ESTest extends CustomerRole_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      BorrowerRole borrowerRole0 = new BorrowerRole();
      assertEquals("Customer{roles=[]}", borrowerRole0.toString());
  }
}
