/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 11 05:13:44 GMT 2021
 */

package concreteextensions;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import concreteextensions.Commander;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import units.CommanderUnit;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Commander_ESTest extends Commander_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CommanderUnit commanderUnit0 = new CommanderUnit("zg`DFP_;)u2");
      Commander commander0 = new Commander(commanderUnit0);
      commander0.commanderReady();
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      CommanderUnit commanderUnit0 = new CommanderUnit("zg`DFP_;)u2");
      Commander commander0 = new Commander(commanderUnit0);
      CommanderUnit commanderUnit1 = commander0.getUnit();
      assertSame(commanderUnit0, commanderUnit1);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Commander commander0 = new Commander((CommanderUnit) null);
      CommanderUnit commanderUnit0 = commander0.getUnit();
      assertNull(commanderUnit0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Commander commander0 = new Commander((CommanderUnit) null);
      // Undeclared exception!
      try { 
        commander0.commanderReady();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Cannot invoke \"units.CommanderUnit.getName()\" because \"this.unit\" is null
         //
         verifyException("concreteextensions.Commander", e);
      }
  }
}
