/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 11 11:16:24 GMT 2021
 */

package com.iluwatar.prototype;

import org.junit.Test;
import static org.junit.Assert.*;
import com.iluwatar.prototype.ElfMage;
import com.iluwatar.prototype.Mage;
import com.iluwatar.prototype.OrcMage;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Mage_ESTest extends Mage_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ElfMage elfMage0 = new ElfMage("e/?*!%#;\"s");
      Mage mage0 = elfMage0.copy();
      assertNotSame(mage0, elfMage0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      OrcMage orcMage0 = new OrcMage("Elven mage helps in e/?*!%#;\"s");
      boolean boolean0 = orcMage0.equals("Elven mage helps in e/?*!%#;\"s");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ElfMage elfMage0 = new ElfMage("e/?*!%#;\"s");
      boolean boolean0 = elfMage0.equals((Object) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ElfMage elfMage0 = new ElfMage((String) null);
      ElfMage elfMage1 = new ElfMage(elfMage0);
      boolean boolean0 = elfMage1.equals(elfMage0);
      assertTrue(boolean0);
  }
}
