/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 11 10:27:50 GMT 2021
 */

package com.iluwatar.partialresponse;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.iluwatar.partialresponse.FieldJsonMapper;
import com.iluwatar.partialresponse.Video;
import com.iluwatar.partialresponse.VideoResource;
import java.util.HashMap;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class VideoResource_ESTest extends VideoResource_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      FieldJsonMapper fieldJsonMapper0 = new FieldJsonMapper();
      HashMap<Integer, Video> hashMap0 = new HashMap<Integer, Video>();
      VideoResource videoResource0 = new VideoResource(fieldJsonMapper0, hashMap0);
      Integer integer0 = new Integer(1918);
      Video video0 = new Video(integer0, "t5QU[om.}A", integer0, "t5QU[om.}A", "", "t5QU[om.}A");
      hashMap0.put(integer0, video0);
      String[] stringArray0 = new String[0];
      String string0 = videoResource0.getDetails(integer0, stringArray0);
      assertEquals("{\"id\": 1918,\"title\": \"t5QU[om.}A\",\"length\": 1918,\"description\": \"t5QU[om.}A\",\"director\": \"\",\"language\": \"t5QU[om.}A\",}", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      String[] stringArray0 = new String[0];
      FieldJsonMapper fieldJsonMapper0 = new FieldJsonMapper();
      HashMap<Integer, Video> hashMap0 = new HashMap<Integer, Video>();
      VideoResource videoResource0 = new VideoResource(fieldJsonMapper0, hashMap0);
      try { 
        videoResource0.getDetails((Integer) null, stringArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // Cannot invoke \"com.iluwatar.partialresponse.Video.toString()\" because the return value of \"java.util.Map.get(Object)\" is null
         //
         verifyException("com.iluwatar.partialresponse.VideoResource", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      String[] stringArray0 = new String[1];
      FieldJsonMapper fieldJsonMapper0 = new FieldJsonMapper();
      HashMap<Integer, Video> hashMap0 = new HashMap<Integer, Video>();
      VideoResource videoResource0 = new VideoResource(fieldJsonMapper0, hashMap0);
      try { 
        videoResource0.getDetails((Integer) null, stringArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      FieldJsonMapper fieldJsonMapper0 = new FieldJsonMapper();
      HashMap<Integer, Video> hashMap0 = new HashMap<Integer, Video>();
      VideoResource videoResource0 = new VideoResource(fieldJsonMapper0, hashMap0);
      String[] stringArray0 = new String[1];
      stringArray0[0] = "&zS=m3x!U";
      try { 
        videoResource0.getDetails((Integer) null, stringArray0);
        fail("Expecting exception: NoSuchFieldException");
      
      } catch(NoSuchFieldException e) {
      }
  }
}
