/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 11 05:36:01 GMT 2021
 */

package com.iluwatar.featuretoggle.pattern.propertiesversion;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.iluwatar.featuretoggle.pattern.propertiesversion.PropertiesFeatureToggleVersion;
import java.util.Properties;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class PropertiesFeatureToggleVersion_ESTest extends PropertiesFeatureToggleVersion_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      PropertiesFeatureToggleVersion propertiesFeatureToggleVersion0 = null;
      try {
        propertiesFeatureToggleVersion0 = new PropertiesFeatureToggleVersion((Properties) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // No Properties Provided.
         //
         verifyException("com.iluwatar.featuretoggle.pattern.propertiesversion.PropertiesFeatureToggleVersion", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Properties properties0 = new Properties();
      PropertiesFeatureToggleVersion propertiesFeatureToggleVersion0 = null;
      try {
        propertiesFeatureToggleVersion0 = new PropertiesFeatureToggleVersion(properties0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Invalid Enhancement Settings Provided.
         //
         verifyException("com.iluwatar.featuretoggle.pattern.propertiesversion.PropertiesFeatureToggleVersion", e);
      }
  }
}
