/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 11 06:04:38 GMT 2021
 */

package com.iluwatar.gameloop;

import org.junit.Test;
import static org.junit.Assert.*;
import com.iluwatar.gameloop.GameController;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class GameController_ESTest extends GameController_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      GameController gameController0 = new GameController();
      gameController0.moveBullet(1.0F);
      float float0 = gameController0.getBulletPosition();
      assertEquals(1.0F, float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      GameController gameController0 = new GameController();
      gameController0.moveBullet((-2053.692F));
      float float0 = gameController0.getBulletPosition();
      assertEquals((-2053.692F), float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      GameController gameController0 = new GameController();
      float float0 = gameController0.getBulletPosition();
      assertEquals(0.0F, float0, 0.01F);
  }
}
