/*
 * This file was automatically generated by EvoSuite
 * Mon Jan 11 11:34:46 GMT 2021
 */

package com.iluwatar.reactor.app;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.iluwatar.reactor.app.AppClient;
import java.util.concurrent.RejectedExecutionException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class AppClient_ESTest extends AppClient_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      AppClient.UdpLoggingClient appClient_UdpLoggingClient0 = new AppClient.UdpLoggingClient("]8UaltIP$", 2701);
      appClient_UdpLoggingClient0.run();
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      AppClient appClient0 = new AppClient();
      appClient0.start();
      appClient0.stop();
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      AppClient appClient0 = new AppClient();
      appClient0.stop();
      // Undeclared exception!
      try { 
        appClient0.start();
        fail("Expecting exception: RejectedExecutionException");
      
      } catch(RejectedExecutionException e) {
         //
         // Task com.iluwatar.reactor.app.AppClient$TcpLoggingClient@2 rejected from java.util.concurrent.ThreadPoolExecutor@14c1294[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
         //
         verifyException("java.util.concurrent.ThreadPoolExecutor$AbortPolicy", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      AppClient.TcpLoggingClient appClient_TcpLoggingClient0 = new AppClient.TcpLoggingClient("", 1);
      // Undeclared exception!
      try { 
        appClient_TcpLoggingClient0.run();
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // java.io.IOException: Remote address/port is not opened: org.evosuite.runtime.vnet.EndPointInfo@7ef09a2b
         //
         verifyException("com.iluwatar.reactor.app.AppClient$TcpLoggingClient", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      String[] stringArray0 = new String[2];
      AppClient.main(stringArray0);
      assertEquals(2, stringArray0.length);
  }
}
